Repository langchain4j/langchain4j, pull requests merged in 2024-10, with the labels that each got.

#1871 Bump com.azure:azure-identity from 1.13.3 to 1.14.0
  langchain4j-parent/pom.xml
Labels: Azure

#1856 Bump com.azure:azure-search-documents from 11.7.1 to 11.7.2
  langchain4j-parent/pom.xml
Labels: Azure

#1873 Fix #1863: Allow using Map<K,V> as a return type of AI Service method.
  docs/docs/tutorials/5-ai-services.md
  langchain4j-core/src/main/java/dev/langchain4j/internal/GsonJsonCodec.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/Json.java
  langchain4j/src/main/java/dev/langchain4j/service/output/ServiceOutputParser.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesIT.java
Labels: P2

#1872 Bump com.azure:azure-ai-inference from 1.0.0-beta.1 to 1.0.0-beta.2
  langchain4j-github-models/pom.xml
Labels: Azure

#1888 Fix: #1875 throw exception if reason is other than CONTENT_FILTER
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/ChatModelListenerIT.java
Labels: Azure

#1854 Fix error handling of AzureOpenAiChatModelListenerIT
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelListenerIT.java
Labels: P2, Azure

#1843 Bringing back public access to the methods of the OllamaModelsBuilder class.
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModelCard.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModelDetails.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModels.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaModelsIT.java
Labels: P2

#1892 Bump com.azure:azure-storage-blob from 12.28.0 to 12.28.1
  langchain4j-parent/pom.xml
Labels: Azure

#1891 Bump com.azure:azure-storage-common from 12.27.0 to 12.27.1
  langchain4j-parent/pom.xml
Labels: Azure

#1852 Milvus: configurable field names
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/CollectionOperationsExecutor.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/CollectionRequestBuilder.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/FieldDefinition.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/Mapper.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStore.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusMetadataFilterMapper.java
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreIT.java
Labels: P2, P3

#1895 Update to Elasticsearch client 8.15.2
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchConfigurationScript.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchMetadataFilterMapper.java
  langchain4j-parent/pom.xml
Labels: Elasticsearch

#1818 Adding Callback Support for Tool Execution (Stream Mode)
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceStreamingResponseHandler.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStream.java
  langchain4j/src/main/java/dev/langchain4j/service/TokenStream.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesWithToolsExecuteCallbackIT.java
Labels: P2, P3

#1913 Always run unit tests on CI, upgrade to JDK 17
  .github/workflows/javadoc.yaml
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  .github/workflows/receive-pr.yml
  .github/workflows/release.yaml
  .github/workflows/release_core_and_parent.yaml
  .github/workflows/snapshot_release.yaml
  .github/workflows/snapshot_release_core_and_parent.yaml
  code-execution-engines/langchain4j-code-execution-engine-graalvm-polyglot/pom.xml
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiTokenizerIT.java
  langchain4j-opensearch/pom.xml
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/CommonTestOperations.java
  langchain4j-parent/pom.xml
Labels: P2

#1931 Convert awaitUntilAsserted to util
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverRemovalIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreRemovalIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithFilteringIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithRemovalIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithoutMetadataIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/TestUtils.java
  langchain4j-mongodb-atlas/src/test/java/dev/langchain4j/store/embedding/mongodb/MongoDbEmbeddingStoreLocalIT.java
Labels: Azure

#1923 #1506 refactor enforcer plugin
  code-execution-engines/langchain4j-code-execution-engine-graalvm-polyglot/pom.xml
  code-execution-engines/langchain4j-code-execution-engine-judge0/pom.xml
  document-loaders/langchain4j-document-loader-amazon-s3/pom.xml
  document-loaders/langchain4j-document-loader-azure-storage-blob/pom.xml
  document-loaders/langchain4j-document-loader-github/pom.xml
  document-loaders/langchain4j-document-loader-google-cloud-storage/pom.xml
  document-loaders/langchain4j-document-loader-selenium/pom.xml
  document-loaders/langchain4j-document-loader-tencent-cos/pom.xml
  document-parsers/langchain4j-document-parser-apache-pdfbox/pom.xml
  document-parsers/langchain4j-document-parser-apache-poi/pom.xml
  document-parsers/langchain4j-document-parser-apache-tika/pom.xml
  embedding-store-filter-parsers/langchain4j-embedding-store-filter-parser-sql/pom.xml
  experimental/langchain4j-experimental-sql/pom.xml
  langchain4j-anthropic/pom.xml
  langchain4j-azure-ai-search/pom.xml
  langchain4j-azure-cosmos-mongo-vcore/pom.xml
  langchain4j-azure-cosmos-nosql/pom.xml
  langchain4j-azure-open-ai/pom.xml
  langchain4j-bedrock/pom.xml
  langchain4j-cassandra/pom.xml
  langchain4j-chatglm/pom.xml
  langchain4j-chroma/pom.xml
  langchain4j-cohere/pom.xml
  langchain4j-core/pom.xml
  langchain4j-easy-rag/pom.xml
  langchain4j-elasticsearch/pom.xml
  langchain4j-github-models/pom.xml
  langchain4j-hugging-face/pom.xml
  langchain4j-infinispan/pom.xml
  langchain4j-milvus/pom.xml
  langchain4j-mistral-ai/pom.xml
  langchain4j-mongodb-atlas/pom.xml
  langchain4j-neo4j/pom.xml
  langchain4j-nomic/pom.xml
  langchain4j-ollama/pom.xml
  langchain4j-open-ai/pom.xml
  langchain4j-opensearch/pom.xml
  langchain4j-parent/pom.xml
  langchain4j-pgvector/pom.xml
  langchain4j-pinecone/pom.xml
  langchain4j-qdrant/pom.xml
  langchain4j-qianfan/pom.xml
  langchain4j-redis/pom.xml
  langchain4j-vearch/pom.xml
  langchain4j-vertex-ai-gemini/pom.xml
  langchain4j-vertex-ai/pom.xml
  langchain4j-vespa/pom.xml
  langchain4j-voyage-ai/pom.xml
  langchain4j-weaviate/pom.xml
  langchain4j-workers-ai/pom.xml
  langchain4j-zhipu-ai/pom.xml
  langchain4j/pom.xml
  web-search-engines/langchain4j-web-search-engine-google-custom/pom.xml
  web-search-engines/langchain4j-web-search-engine-searchapi/pom.xml
  web-search-engines/langchain4j-web-search-engine-tavily/pom.xml
Labels: Azure, Gemini

#1907 feat: Tracking input tokens on embeddings store ingestor
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/EmbeddingStoreIngestor.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/IngestionResult.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreIngestorTest.java
Labels: P2, P3

#1945 Migrated the "responsible AI" integration tests to GitHub Models
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAIResponsibleAIIT.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/AzureResponsibleAIIT.java
Labels: Azure

#1955 #1929 tinylog level surefire
  .github/workflows/main.yaml
  .mvn/jvm.config
  experimental/langchain4j-experimental-sql/pom.xml
  langchain4j-azure-ai-search/pom.xml
  langchain4j-bedrock/pom.xml
  langchain4j-bom/pom.xml
  langchain4j-cassandra/pom.xml
  langchain4j-core/pom.xml
  langchain4j-easy-rag/pom.xml
  langchain4j-google-ai-gemini/pom.xml
  langchain4j-jlama/pom.xml
  langchain4j-local-ai/pom.xml
  langchain4j-neo4j/pom.xml
  langchain4j-onnx-scoring/pom.xml
  langchain4j-open-ai/pom.xml
  langchain4j-parent/pom.xml
  langchain4j-vertex-ai-gemini/pom.xml
  langchain4j-zhipu-ai/pom.xml
  langchain4j/pom.xml
  pom.xml
  web-search-engines/langchain4j-web-search-engine-google-custom/pom.xml
Labels: Azure, Gemini

#1949 Fix #1747
  docs/docs/integrations/embedding-stores/pinecone.md
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaClient.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreIT.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/Mapper.java
  langchain4j-pgvector/src/test/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStoreWithColumnsFilteringIT.java
  langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStore.java
  langchain4j-pinecone/src/test/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStoreIT.java
  langchain4j-weaviate/src/test/java/dev/langchain4j/store/embedding/weaviate/LocalWeaviateEmbeddingStoreIT.java
Labels: P1, P2, RAG

#1809 `langchain4j-vearch` get rid of lombok
  langchain4j-vearch/pom.xml
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/BulkRequest.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/BulkResponse.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/CreateDatabaseRequest.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/CreateDatabaseResponse.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/CreateSpaceRequest.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/CreateSpaceResponse.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/ListDatabaseResponse.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/ListSpaceResponse.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/ModelParam.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/ResponseWrapper.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/RetrievalParam.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/SearchRequest.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/SearchResponse.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/SpaceEngine.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/SpacePropertyParam.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/SpaceStoreParam.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/VearchClient.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/VearchConfig.java
  langchain4j-vearch/src/main/java/dev/langchain4j/store/embedding/vearch/VearchEmbeddingStore.java
  langchain4j-vearch/src/test/java/dev/langchain4j/store/embedding/vearch/VearchContainer.java
  langchain4j-vearch/src/test/java/dev/langchain4j/store/embedding/vearch/VearchEmbeddingStoreIT.java
Labels: P3

#1950 Google AI Gemini: replace OkHttp and Retrofit with Java 11 HttpClient
  langchain4j-google-ai-gemini/pom.xml
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GeminiService.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiEmbeddingModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiTokenizer.java
Labels: Gemini

#1981 [Bug] Fix #1340
  langchain4j-redis/src/main/java/dev/langchain4j/store/embedding/redis/RedisEmbeddingStore.java
  langchain4j-redis/src/main/java/dev/langchain4j/store/embedding/redis/RedisSchema.java
  langchain4j-redis/src/test/java/dev/langchain4j/store/embedding/redis/RedisEmbeddingStoreIT.java
Labels: P2

#1978 Run under JDK 23
  .github/workflows/main.yaml
Labels: P3
