Repository langchain4j/langchain4j, pull requests merged in 2024-11, with the labels that each got.

#2023 Bump com.azure:azure-search-documents from 11.7.2 to 11.7.3
  langchain4j-parent/pom.xml
Labels: Azure

#2032 Bump com.azure:azure-identity from 1.14.0 to 1.14.1
  langchain4j-parent/pom.xml
Labels: Azure

#2003 Add Oracle Coherence embedding store implementation
  docs/docs/integrations/embedding-stores/coherence.md
  docs/docs/integrations/embedding-stores/index.md
  langchain4j-bom/pom.xml
  langchain4j-coherence/pom.xml
  langchain4j-coherence/src/main/java/dev/langchain4j/store/embedding/coherence/CoherenceEmbeddingStore.java
  langchain4j-coherence/src/main/java/dev/langchain4j/store/embedding/coherence/CoherenceMetadataFilterMapper.java
  langchain4j-coherence/src/main/java/dev/langchain4j/store/memory/chat/coherence/CoherenceChatMemoryStore.java
  langchain4j-coherence/src/test/java/dev/langchain4j/store/embedding/coherence/CoherenceEmbeddingStoreIT.java
  langchain4j-coherence/src/test/java/dev/langchain4j/store/embedding/coherence/CoherenceEmbeddingStoreRemovalIT.java
  langchain4j-coherence/src/test/java/dev/langchain4j/store/memory/chat/coherence/CoherenceChatMemoryStoreIT.java
  pom.xml
Labels: P2, P3

#2029 Add Jlama v0.8.2 and improve tool/model support
  langchain4j-jlama/pom.xml
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaAiServicesWithToolsIT.java
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaChatModelIT.java
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaChatModelToolsIT.java
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaLanguageModelIT.java
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaStreamingChatModelIT.java
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaStreamingLanguageModelIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/LangChain4jOllamaContainer.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaToolChatModelIT.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/DefaultToolExecutor.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithNewToolsIT.java
Labels: P2

#1746 langchain4j-chatglm get rid of lombok
  langchain4j-chatglm/pom.xml
  langchain4j-chatglm/src/main/java/dev/langchain4j/model/chatglm/ChatCompletionRequest.java
  langchain4j-chatglm/src/main/java/dev/langchain4j/model/chatglm/ChatCompletionResponse.java
  langchain4j-chatglm/src/main/java/dev/langchain4j/model/chatglm/ChatGlmChatModel.java
  langchain4j-chatglm/src/main/java/dev/langchain4j/model/chatglm/ChatGlmClient.java
  langchain4j-chatglm/src/main/java/dev/langchain4j/model/chatglm/ChatGlmRequestLoggingInterceptor.java
  langchain4j-chatglm/src/main/java/dev/langchain4j/model/chatglm/ChatGlmResponseLoggingInterceptor.java
  langchain4j-chatglm/src/test/java/dev/langchain4j/model/chatglm/ChatGlmChatModelIT.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/Function.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaApiIT.java
Labels: P3

#2028 Marked obvious `@Deprecated` candidates `forRemoval = true`
  document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiModelName.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-cohere/src/main/java/dev/langchain4j/model/cohere/CohereEmbeddingModel.java
  langchain4j-cohere/src/main/java/dev/langchain4j/model/cohere/CohereScoringModel.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/JsonSchemaProperty.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolParameters.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolSpecification.java
  langchain4j-core/src/main/java/dev/langchain4j/data/document/Document.java
  langchain4j-core/src/main/java/dev/langchain4j/data/document/Metadata.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/ChatMessage.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/UserMessage.java
  langchain4j-core/src/main/java/dev/langchain4j/data/segment/TextSegment.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/Json.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/Utils.java
  langchain4j-core/src/main/java/dev/langchain4j/model/output/TokenUsage.java
  langchain4j-core/src/main/java/dev/langchain4j/retriever/EmbeddingStoreRetriever.java
  langchain4j-core/src/main/java/dev/langchain4j/retriever/Retriever.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStore.java
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/JinaEmbeddingModel.java
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/JinaScoringModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiChatModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiChatModelName.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiEmbeddingModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiModels.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiStreamingChatModel.java
  langchain4j-nomic/src/main/java/dev/langchain4j/model/nomic/NomicEmbeddingModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModelName.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiEmbeddingModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiImageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiLanguageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiModelName.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiModerationModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingLanguageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiTokenizer.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/OvhAiEmbeddingModel.java
  langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStore.java
  langchain4j/src/main/java/dev/langchain4j/chain/ConversationalRetrievalChain.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
Labels: Azure

#2054 issue with TextDocumentParser PR
  langchain4j/src/main/java/dev/langchain4j/data/document/parser/TextDocumentParser.java
Labels: P2, P3

#1788 Weaviate: configurable metadata keys
  docs/docs/integrations/embedding-stores/weaviate.md
  langchain4j-weaviate/src/main/java/dev/langchain4j/store/embedding/weaviate/WeaviateEmbeddingStore.java
  langchain4j-weaviate/src/test/java/dev/langchain4j/store/embedding/weaviate/LocalWeaviateMetadataAtBaseStoreIT.java
Labels: P2, P3

#2042 Milvus: option to set MilvusServiceClient
  docs/docs/integrations/embedding-stores/milvus.md
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStore.java
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreIT.java
Labels: P2, P3

#2055 mistral integrate moderation
  docs/docs/integrations/language-models/mistral-ai.md
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiChatModelName.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiModerationModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiApi.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiModerationRequest.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiModerationResponse.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralCategories.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralCategoryScores.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralModerationResult.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/client/DefaultMistralAiClient.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/client/MistralAiClient.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiModerationModelIT.java
Labels: P2, P3

#2105 #1636 add lombok annotation processor
  langchain4j-parent/pom.xml
Labels: Gemini

#2064 Remove Lombok in LC4J-open-ai
  langchain4j-open-ai/pom.xml
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/InternalOpenAiHelper.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiEmbeddingModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiImageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiLanguageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiModerationModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingLanguageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiTokenizer.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelListenerIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiEmbeddingModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiImageModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiLanguageModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiModerationModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelListenerIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingLanguageModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiTokenizerIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiTokenizerTest.java
  langchain4j/src/main/java/dev/langchain4j/classification/EmbeddingModelTextClassifier.java
  langchain4j/src/main/java/dev/langchain4j/classification/TextClassifier.java
  langchain4j/src/main/java/dev/langchain4j/data/document/loader/UrlDocumentLoader.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/HierarchicalDocumentSplitter.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/SegmentBuilder.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/Result.java
  langchain4j/src/main/java/dev/langchain4j/service/TypeUtils.java
  langchain4j/src/main/java/dev/langchain4j/service/output/JsonSchemas.java
  langchain4j/src/main/java/dev/langchain4j/service/output/OutputParser.java
  langchain4j/src/main/java/dev/langchain4j/service/output/ServiceOutputParser.java
  langchain4j/src/test/java/dev/langchain4j/chain/ConversationalChainTest.java
  langchain4j/src/test/java/dev/langchain4j/chain/ConversationalRetrievalChainTest.java
  langchain4j/src/test/java/dev/langchain4j/classification/TextClassifierTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/loader/FileSystemDocumentLoaderTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/loader/UrlDocumentLoaderTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/parser/TextDocumentParserTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/HierarchicalDocumentSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/SegmentBuilderTest.java
  langchain4j/src/test/java/dev/langchain4j/exception/IllegalConfigurationExceptionTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsWithoutMemoryIT.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesIT.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesWithToolsWithoutMemoryIT.java
  langchain4j/src/test/java/dev/langchain4j/service/TypeUtilsTest.java
  langchain4j/src/test/java/dev/langchain4j/service/tool/ToolExecutionRequestUtilTest.java
  langchain4j/src/test/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStoreRemovalTest.java
  langchain4j/src/test/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStoreTest.java
Labels: P2, P3

#2147 Bump com.azure:azure-identity from 1.14.1 to 1.14.2
  langchain4j-parent/pom.xml
Labels: Azure

#2125 Bumps com.azure:azure-storage-blob from 12.28.1 to 12.29.0
  langchain4j-parent/pom.xml
Labels: Azure

#2126 Bumps com.azure:azure-storage-common from 12.27.1 to 12.28.0
  langchain4j-parent/pom.xml
Labels: Azure

#1901 [DEPENDENCIES] Upgrade Kotlin version to 2.0.21 for #1897, cleanup dependencies, upgrade Milvus and Guava
  code-execution-engines/langchain4j-code-execution-engine-judge0/pom.xml
  langchain4j-anthropic/pom.xml
  langchain4j-chroma/pom.xml
  langchain4j-cohere/pom.xml
  langchain4j-hugging-face/pom.xml
  langchain4j-jina/pom.xml
  langchain4j-jlama/pom.xml
  langchain4j-mistral-ai/pom.xml
  langchain4j-nomic/pom.xml
  langchain4j-ollama/pom.xml
  langchain4j-open-ai/pom.xml
  langchain4j-ovh-ai/pom.xml
  langchain4j-parent/pom.xml
  langchain4j-vespa/pom.xml
  langchain4j-voyage-ai/pom.xml
  langchain4j-workers-ai/pom.xml
  web-search-engines/langchain4j-web-search-engine-searchapi/pom.xml
  web-search-engines/langchain4j-web-search-engine-tavily/pom.xml
Labels: P2, P3

#2179 feat: Qdrant Embedding Removal
  langchain4j-qdrant/src/main/java/dev/langchain4j/store/embedding/qdrant/QdrantEmbeddingStore.java
  langchain4j-qdrant/src/test/java/dev/langchain4j/store/embedding/qdrant/QdrantEmbeddingStoreWithRemovalIT.java
Labels: P2, P3

#2197 #1897 Add Kotlin dependencies, plugins, and extensions
  .editorconfig
  .mvn/jvm.config
  detekt.yml
  docs/docs/intro.md
  docs/docs/tutorials/1-chat-and-language-models.md
  docs/docs/tutorials/kotlin.md
  langchain4j-core/pom.xml
  langchain4j-core/src/main/kotlin/dev/langchain4j/model/chat/ChatLanguageModelExtensions.kt
  langchain4j-core/src/test/kotlin/dev/langchain4j/model/chat/ChatLanguageModelExtensionsTest.kt
  langchain4j-parent/pom.xml
Labels: P2, P3
