Repository langchain4j/langchain4j, pull requests merged in 2024-05, with the labels that each got.

#642 [FEATURE] WebSearchEngine as ContentRetriver and tool
  docs/static/img/web-search-engine.png
  langchain4j-core/pom.xml
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/retriever/ContentRetriever.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/retriever/WebSearchContentRetriever.java
  langchain4j-core/src/main/java/dev/langchain4j/web/search/WebSearchEngine.java
  langchain4j-core/src/main/java/dev/langchain4j/web/search/WebSearchInformationResult.java
  langchain4j-core/src/main/java/dev/langchain4j/web/search/WebSearchOrganicResult.java
  langchain4j-core/src/main/java/dev/langchain4j/web/search/WebSearchRequest.java
  langchain4j-core/src/main/java/dev/langchain4j/web/search/WebSearchResults.java
  langchain4j-core/src/main/java/dev/langchain4j/web/search/WebSearchTool.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/retriever/WebSearchContentRetrieverIT.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/retriever/WebSearchContentRetrieverTest.java
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchEngineIT.java
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchInformationResultTest.java
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchOrganicResultTest.java
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchRequestTest.java
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchResultsTest.java
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchToolIT.java
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchToolTest.java
Labels: P2

#1031 [BUG] Introduce parser supplier support in FileSystemDocumentLoader
  document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java
  document-parsers/langchain4j-document-parser-apache-tika/src/test/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParserTest.java
Labels: P1

#981 Bugfix/fix 0 retry times
  langchain4j-core/src/main/java/dev/langchain4j/internal/RetryUtils.java
  langchain4j-core/src/test/java/dev/langchain4j/internal/RetryUtilsTest.java
Labels: P2

#1043 Migrate Anthropic from Gson to Jackson
  langchain4j-anthropic/pom.xml
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicCreateMessageRequest.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicCreateMessageResponse.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicDelta.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicImageContentSource.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicMessage.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicMessageContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicResponseMessage.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicRole.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTextContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTool.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicToolSchema.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicUsage.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicApi.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicCreateMessageRequest.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicCreateMessageResponse.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicDelta.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicImageContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicImageContentSource.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicMessage.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicMessageContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicResponseMessage.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicRole.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicStreamingData.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicTextContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicTool.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicToolResultContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicToolSchema.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicToolUseContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicUsage.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicClient.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicClientBuilderFactory.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicHttpException.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicRequestLoggingInterceptor.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicResponseLoggingInterceptor.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/DefaultAnthropicClient.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/mapper/AnthropicMapper.java
  langchain4j-anthropic/src/main/resources/META-INF/native-image/dev.langchain4j/langchain4j-anthropic/proxy-config.json
  langchain4j-anthropic/src/main/resources/META-INF/native-image/dev.langchain4j/langchain4j-anthropic/reflect-config.json
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicMapperTest.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/internal/client/AnthropicRequestLoggingInterceptorTest.java
  langchain4j-parent/pom.xml
Labels: P2

#911 Ollama add OkhttpClient inject
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaEmbeddingModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaLanguageModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingLanguageModel.java
Labels: P2

#529 Azure OpenAI: migrate to the new API, from "function" to "tools"
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelperTest.java
  langchain4j-parent/pom.xml
Labels: P2

#1015 [FEATURE] Retrieve Documents when using AiService
  docs/docs/tutorials/5-ai-services.md
  docs/docs/tutorials/7-rag.md
  langchain4j-core/src/main/java/dev/langchain4j/rag/AugmentationRequest.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/AugmentationResult.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/DefaultRetrievalAugmentor.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/RetrievalAugmentor.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/injector/ContentInjector.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/injector/DefaultContentInjector.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/DefaultRetrievalAugmentorTest.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j/src/main/java/dev/langchain4j/chain/ConversationalRetrievalChain.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/Result.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithRagIT.java
Labels: P1, P2

#1054 Handle misconfigured tools
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesBuilderTest.java
Labels: P2

#1051 Extract Judge0 code execution engine as module
  code-execution-engines/langchain4j-code-execution-engine-judge0/pom.xml
  code-execution-engines/langchain4j-code-execution-engine-judge0/src/main/java/dev/langchain4j/code/JavaScriptCodeFixer.java
  code-execution-engines/langchain4j-code-execution-engine-judge0/src/main/java/dev/langchain4j/code/Judge0JavaScriptEngine.java
  code-execution-engines/langchain4j-code-execution-engine-judge0/src/main/java/dev/langchain4j/code/Judge0JavaScriptExecutionTool.java
  code-execution-engines/langchain4j-code-execution-engine-judge0/src/test/java/dev/langchain4j/code/JavaScriptCodeFixerTest.java
  langchain4j/pom.xml
  pom.xml
Labels: P2

#641 [FEATURE] Google web search integration
  langchain4j-bom/pom.xml
  pom.xml
  web-searchers/langchain4j-web-search-engine-google-custom/pom.xml
  web-searchers/langchain4j-web-search-engine-google-custom/src/main/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomSearchApiClient.java
  web-searchers/langchain4j-web-search-engine-google-custom/src/main/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchEngine.java
  web-searchers/langchain4j-web-search-engine-google-custom/src/main/java/dev/langchain4j/web/search/google/customsearch/GoogleSearchApiHttpRequestLoggingInterceptor.java
  web-searchers/langchain4j-web-search-engine-google-custom/src/main/java/dev/langchain4j/web/search/google/customsearch/GoogleSearchApiHttpResponseLoggingInterceptor.java
  web-searchers/langchain4j-web-search-engine-google-custom/src/test/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchContentRetrieverIT.java
  web-searchers/langchain4j-web-search-engine-google-custom/src/test/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchEngineIT.java
  web-searchers/langchain4j-web-search-engine-google-custom/src/test/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchToolIT.java
Labels: P2

#676 Tavily Web Search Engine
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/retriever/WebSearchContentRetriever.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/retriever/WebSearchContentRetrieverIT.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/retriever/WebSearchContentRetrieverTest.java
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchEngineIT.java
  pom.xml
  web-search-engines/langchain4j-web-search-engine-google-custom/src/test/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchContentRetrieverIT.java
  web-search-engines/langchain4j-web-search-engine-google-custom/src/test/java/dev/langchain4j/web/search/google/customsearch/GoogleCustomWebSearchEngineIT.java
  web-search-engines/langchain4j-web-search-engine-tavily/pom.xml
  web-search-engines/langchain4j-web-search-engine-tavily/src/main/java/dev/langchain4j/web/search/tavily/TavilyApi.java
  web-search-engines/langchain4j-web-search-engine-tavily/src/main/java/dev/langchain4j/web/search/tavily/TavilyClient.java
  web-search-engines/langchain4j-web-search-engine-tavily/src/main/java/dev/langchain4j/web/search/tavily/TavilyResponse.java
  web-search-engines/langchain4j-web-search-engine-tavily/src/main/java/dev/langchain4j/web/search/tavily/TavilySearchRequest.java
  web-search-engines/langchain4j-web-search-engine-tavily/src/main/java/dev/langchain4j/web/search/tavily/TavilySearchResult.java
  web-search-engines/langchain4j-web-search-engine-tavily/src/main/java/dev/langchain4j/web/search/tavily/TavilyWebSearchEngine.java
  web-search-engines/langchain4j-web-search-engine-tavily/src/test/java/dev/langchain4j/web/search/tavily/TavilyWebSearchEngineIT.java
Labels: P2

#1084 AzureAiSearchEmbeddingStore - add "indexName" to the builder
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetriever.java
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStore.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverTest.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreTest.java
Labels: P2

#662 add logs for OllamaClient
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaEmbeddingModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaLanguageModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModels.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaRequestLoggingInterceptor.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaResponseLoggingInterceptor.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingLanguageModel.java
Labels: P3

#997 Jina AI Embedding model integration
  langchain4j-jina/pom.xml
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/EmbeddingRequest.java
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/EmbeddingResponse.java
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/JinaApi.java
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/JinaClient.java
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/JinaEmbedding.java
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/JinaEmbeddingModel.java
  langchain4j-jina/src/main/java/dev/langchain4j/model/jina/Usage.java
  langchain4j-jina/src/test/java/dev/langchain4j/model/jina/JinaEmbeddingModelIT.java
  pom.xml
Labels: P3

#1006 Freature #1005 - Add streaming API for Bedrock Anthropics
  README.md
  langchain4j-bedrock/pom.xml
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicStreamingChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockStreamingChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractSharedBedrockChatModel.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockStreamingChatModelIT.java
Labels: P2

#978 New Mistral open mixtral8x22b model
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiChatModelName.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiChatModelIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiStreamingChatModelIT.java
Labels: P3

#979 [Documentation] Mistral open mixtral8x22b docs
  docs/docs/integrations/language-models/mistral-ai.md
  docs/docs/tutorials/5-ai-services.md
  docs/docs/tutorials/6-tools.md
Labels: P3

#999 Fix: #950 ZhipuAiChatModel does not support tools without parameters
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/DefaultZhipuAiHelper.java
  langchain4j-zhipu-ai/src/test/java/dev/langchain4j/model/zhipu/ZhipuAiChatModelIT.java
  langchain4j-zhipu-ai/src/test/java/dev/langchain4j/model/zhipu/ZhipuAiStreamingChatModelIT.java
Labels: P3
