Repository langchain4j/langchain4j, pull requests merged in 2024-08, with the labels that each got.

#1535 Bump com.azure:azure-storage-common from 12.25.1 to 12.26.0
  langchain4j-parent/pom.xml
Labels: Azure

#1534 Bump com.azure:azure-storage-blob from 12.26.1 to 12.27.0
  langchain4j-parent/pom.xml
Labels: Azure

#1533 Bump com.azure:azure-search-documents from 11.6.6 to 11.7.0
  langchain4j-parent/pom.xml
Labels: Azure

#1563 [FEATURE] Implemented removal methods for AzureAiSearchEmbeddingStore
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverRemovalIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreRemovalIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithRemovalIT.java
Labels: Azure

#1578 added dimensions parameter to specify by user in AzureOpenAiEmbeddingModel
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModel.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModelIT.java
Labels: Azure

#1576 fix bug: AiMessage text content is not copied when toolCalls are pres…
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelperTest.java
Labels: Azure

#1185 support run integration tests for changed and dependent modules
  .github/workflows/main.yaml
  langchain4j-parent/pom.xml
  pom.xml
Labels: P1, P2

#1601 Feature 949 pinecone support metadata filter
  docs/docs/integrations/embedding-stores/index.md
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithFilteringIT.java
  langchain4j-pinecone/pom.xml
  langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStore.java
  langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeMetadataFilterMapper.java
  langchain4j-pinecone/src/test/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStoreIT.java
  langchain4j-pinecone/src/test/java/dev/langchain4j/store/embedding/pinecone/PineconeMetadataFilterMapperTest.java
Labels: P3

#712 Elasticsearch: Add approximative kNN search in addition to Cosine similarity
  docs/docs/integrations/embedding-stores/elasticsearch.md
  langchain4j-elasticsearch/pom.xml
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchConfiguration.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchConfigurationKnn.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchConfigurationScript.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStore.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchRequestFailedException.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/AbstractElasticsearchEmbeddingStoreIT.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchClientHelper.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStoreCloudIT.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStoreIT.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStoreRemoveIT.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchKnnEmbeddingStoreIT.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/SSLUtils.java
  langchain4j-elasticsearch/src/test/resources/log4j2.xml
  langchain4j-elasticsearch/src/test/resources/version.properties
  langchain4j-parent/pom.xml
Labels: P2

#1609 Bump com.azure:azure-identity from 1.13.1 to 1.13.2
  langchain4j-parent/pom.xml
Labels: Azure

#1556 1505-feature-chroma-support-metadata-filtering
  docs/docs/integrations/embedding-stores/chroma.md
  docs/docs/integrations/embedding-stores/index.md
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStore.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaMetadataFilterMapper.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/QueryRequest.java
  langchain4j-chroma/src/test/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStoreIT.java
  langchain4j-chroma/src/test/java/dev/langchain4j/store/embedding/chroma/ChromaMetadataFilterMapperTest.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithFilteringIT.java
Labels: P2

#1216 [FEATURE] Adds SearchApi as WebSearchEngine and Tool
  docs/docs/integrations/web-search/_category_.json
  docs/docs/integrations/web-search/searchapi.md
  langchain4j-bom/pom.xml
  langchain4j-core/src/test/java/dev/langchain4j/web/search/WebSearchEngineIT.java
  pom.xml
  web-search-engines/langchain4j-web-search-engine-searchapi/pom.xml
  web-search-engines/langchain4j-web-search-engine-searchapi/src/main/java/dev/langchain4j/web/search/searchapi/SearchApi.java
  web-search-engines/langchain4j-web-search-engine-searchapi/src/main/java/dev/langchain4j/web/search/searchapi/SearchApiClient.java
  web-search-engines/langchain4j-web-search-engine-searchapi/src/main/java/dev/langchain4j/web/search/searchapi/SearchApiWebSearchEngine.java
  web-search-engines/langchain4j-web-search-engine-searchapi/src/main/java/dev/langchain4j/web/search/searchapi/SearchApiWebSearchRequest.java
  web-search-engines/langchain4j-web-search-engine-searchapi/src/main/java/dev/langchain4j/web/search/searchapi/SearchApiWebSearchResponse.java
  web-search-engines/langchain4j-web-search-engine-searchapi/src/test/java/SearchApiContentRetrieverIT.java
  web-search-engines/langchain4j-web-search-engine-searchapi/src/test/java/SearchApiWebSearchEngineIT.java
  web-search-engines/langchain4j-web-search-engine-searchapi/src/test/java/SearchApiWebSearchToolIT.java
Labels: P2, P3

#1610 EmbeddingStoreIT: use awaitility
  docs/docs/integrations/embedding-stores/index.md
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverRemovalIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreRemovalIT.java
  langchain4j-azure-cosmos-mongo-vcore/pom.xml
  langchain4j-azure-cosmos-mongo-vcore/src/test/java/dev/langchain4j/store/embedding/azure/cosmos/mongo/vcore/AzureCosmosDBMongoVCoreEmbeddingStoreIT.java
  langchain4j-azure-cosmos-nosql/pom.xml
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDbNoSqlEmbeddingStoreIT.java
  langchain4j-cassandra/pom.xml
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/embedding/astradb/AstraDbEmbeddingStoreIT.java
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/embedding/cassandra/CassandraEmbeddingStoreAstraIT.java
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/embedding/cassandra/CassandraEmbeddingStoreDockerIT.java
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/embedding/cassandra/CassandraEmbeddingStoreIT.java
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/memory/chat/cassandra/CassandraChatMemoryStoreDockerIT.java
  langchain4j-chroma/src/test/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStoreIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithFilteringIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithRemovalIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithoutMetadataIT.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/AbstractElasticsearchEmbeddingStoreIT.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStoreKnnIT.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStoreScriptIT.java
  langchain4j-infinispan/pom.xml
  langchain4j-mongodb-atlas/pom.xml
  langchain4j-mongodb-atlas/src/test/java/dev/langchain4j/store/embedding/mongodb/MongoDbEmbeddingStoreCloudIT.java
  langchain4j-mongodb-atlas/src/test/java/dev/langchain4j/store/embedding/mongodb/MongoDbEmbeddingStoreLocalIT.java
  langchain4j-mongodb-atlas/src/test/java/dev/langchain4j/store/embedding/mongodb/MongoDbEmbeddingStoreNativeFilterIT.java
  langchain4j-neo4j/pom.xml
  langchain4j-neo4j/src/test/java/dev/langchain4j/store/embedding/neo4j/Neo4jEmbeddingStoreIT.java
  langchain4j-opensearch/src/test/java/dev/langchain4j/store/embedding/opensearch/OpenSearchEmbeddingStoreAwsIT.java
  langchain4j-opensearch/src/test/java/dev/langchain4j/store/embedding/opensearch/OpenSearchEmbeddingStoreLocalIT.java
  langchain4j-pinecone/src/test/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStoreIT.java
  langchain4j-qdrant/pom.xml
  langchain4j-redis/pom.xml
  langchain4j-vearch/pom.xml
  langchain4j-vearch/src/test/java/dev/langchain4j/store/embedding/vearch/VearchEmbeddingStoreIT.java
  langchain4j/src/test/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStoreSerializedTest.java
Labels: Azure

#1527 660 : Support for onRetrieved for TokenStream
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStream.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/OnCompleteOrOnError.java
  langchain4j/src/main/java/dev/langchain4j/service/OnError.java
  langchain4j/src/main/java/dev/langchain4j/service/OnStart.java
  langchain4j/src/main/java/dev/langchain4j/service/TokenStream.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServiceTokenStreamTest.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesIT.java
Labels: P1, P2

#1516 1446 : Extraction of json block before parse
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/output/ServiceOutputParser.java
  langchain4j/src/test/java/dev/langchain4j/service/output/ServiceOutputParserTest.java
Labels: P1, P2

#1622 OpenAI: return token usage returned by OpenAI
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingResponseBuilder.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
  langchain4j-parent/pom.xml
Labels: P2

#1637 Bump com.azure:azure-storage-common from 12.26.0 to 12.26.1
  langchain4j-parent/pom.xml
Labels: Azure

#1638 Bumps com.azure:azure-search-documents from 11.7.0 to 11.7.1
  langchain4j-parent/pom.xml
Labels: Azure

#1639 Bumps com.azure:azure-storage-blob from 12.27.0 to 12.27.1
  langchain4j-parent/pom.xml
Labels: Azure

#1509 re #1506 Enabling Maven version enforcer plugin in `LangChain4j :: Integration :: Azure OpenAI` module.
  langchain4j-azure-open-ai/pom.xml
Labels: P2, Azure

#1490 Oracle Database Embedding Store
  docs/docs/integrations/embedding-stores/index.md
  docs/docs/integrations/embedding-stores/oracle.md
  docs/docs/integrations/embedding-stores/pgvector.md
  docs/docs/integrations/embedding-stores/pinecone.md
  docs/docs/integrations/embedding-stores/qdrant.md
  docs/docs/integrations/embedding-stores/redis.md
  docs/docs/integrations/embedding-stores/vearch.md
  docs/docs/integrations/embedding-stores/vespa.md
  docs/docs/integrations/embedding-stores/weaviate.md
  langchain4j-bom/pom.xml
  langchain4j-oracle/README.md
  langchain4j-oracle/pom.xml
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/CreateOption.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/EmbeddingTable.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/OracleEmbeddingStore.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/SQLFilter.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/SQLFilters.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/CommonTestOperations.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/EmbeddingTableTest.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/ExactSearchIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/OracleEmbeddingStoreWithFilteringIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/OracleEmbeddingStoreWithRemovalIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/SQLFilterTest.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/TestData.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/VectorIndexTest.java
  pom.xml
Labels: P2

#1642 Milvus - upgrade to Milvus SDK 2.3.9
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/Generator.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/Mapper.java
  langchain4j-parent/pom.xml
Labels: P2

#1647 Feature 1567 ai services provide information about executed tools
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/Result.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolExecution.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java
Labels: P2
