Repository langchain4j/langchain4j, pull requests merged in 2024-09, with the labels that each got.

#1656 Bump com.azure:azure-ai-openai from 1.0.0-beta.10 to 1.0.0-beta.11
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-parent/pom.xml
Labels: Azure

#1649 Add numCandidates setting to ElasticsearchConfigurationKnn
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchConfigurationKnn.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchClientHelper.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStoreKnnWithConfigurationIT.java
Labels: Elasticsearch

#1482 Adds couchbase vector storage
  docs/docs/integrations/embedding-stores/couchbase.md
  docs/docs/integrations/embedding-stores/elasticsearch.md
  docs/docs/integrations/embedding-stores/index.md
  docs/docs/integrations/embedding-stores/infinispan.md
  docs/docs/integrations/embedding-stores/milvus.md
  docs/docs/integrations/embedding-stores/mongodb-atlas.md
  docs/docs/integrations/embedding-stores/neo4j.md
  docs/docs/integrations/embedding-stores/opensearch.md
  langchain4j-bom/pom.xml
  langchain4j-couchbase/pom.xml
  langchain4j-couchbase/src/main/java/dev/langchain4j/store/embedding/couchbase/CouchbaseEmbeddingStore.java
  langchain4j-couchbase/src/main/java/dev/langchain4j/store/embedding/couchbase/Document.java
  langchain4j-couchbase/src/test/java/dev/langchain4j/store/embedding/couchbase/CouchbaseEmbeddingStoreCloudIT.java
  langchain4j-couchbase/src/test/java/dev/langchain4j/store/embedding/couchbase/CouchbaseEmbeddingStoreIT.java
  langchain4j-couchbase/src/test/java/dev/langchain4j/store/embedding/couchbase/CouchbaseEmbeddingStoreWithRemovalCloudIT.java
  langchain4j-couchbase/src/test/java/dev/langchain4j/store/embedding/couchbase/CouchbaseEmbeddingStoreWithRemovalIT.java
  langchain4j-couchbase/src/test/java/dev/langchain4j/store/embedding/couchbase/CouchbaseTestUtils.java
  pom.xml
Labels: P3

#1671 langchain4j-elasticsearch get rid of lombok
  langchain4j-elasticsearch/pom.xml
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/Document.java
Labels: Elasticsearch

#1475 [Feature] ApachePdfBoxDocumentParser should return metadata
  document-parsers/langchain4j-document-parser-apache-pdfbox/src/main/java/dev/langchain4j/data/document/parser/apache/pdfbox/ApachePdfBoxDocumentParser.java
  document-parsers/langchain4j-document-parser-apache-pdfbox/src/test/java/dev/langchain4j/data/document/parser/apache/pdfbox/ApachePdfBoxDocumentParserTest.java
Labels: P3

#1644 [FEATURE] Select tools dynamically on incoming message
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceContext.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceStreamingResponseHandler.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStream.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolProvider.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolProviderRequest.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolProviderResult.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesWithToolsIT.java
Labels: P1, P2

#1708 Gemini AI: improve error reporting and flags for Python code execution
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/FunctionMapper.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GeminiError.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GeminiErrorContainer.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/PartsAndContentsMapper.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelIT.java
Labels: Gemini

#1721 Documentation for the Google AI Gemini module
  docs/docs/integrations/language-models/google-ai-gemini.md
Labels: Gemini

#1732 bug(Google AI Gemini) — fix mapping for tools with parameters with nested object structures
  langchain4j-core/src/main/java/dev/langchain4j/internal/TypeUtils.java
  langchain4j-core/src/test/java/dev/langchain4j/internal/TypeUtilsTest.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/FunctionMapper.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GeminiType.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/FunctionMapperTest.java
  langchain4j/src/main/java/dev/langchain4j/service/output/JsonSchemas.java
Labels: Gemini

#1720 fix error handling on azure streaming responses when content filter applied
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
Labels: Azure

#1730 Migrated Bedrock from Gson to Jackson.
  langchain4j-bedrock/pom.xml
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockMistralAiChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockEmbeddingModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockStreamingChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractSharedBedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/Json.java
Labels: P2

#1729 Judge0: migrate from Gson to Jackson
  code-execution-engines/langchain4j-code-execution-engine-judge0/pom.xml
  code-execution-engines/langchain4j-code-execution-engine-judge0/src/main/java/dev/langchain4j/code/judge0/Json.java
  code-execution-engines/langchain4j-code-execution-engine-judge0/src/main/java/dev/langchain4j/code/judge0/Judge0JavaScriptEngine.java
Labels: P2

#1728 Migrage huggingface from Gson to Jackson
  langchain4j-hugging-face/pom.xml
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/DefaultHuggingFaceClient.java
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/HuggingFaceChatModel.java
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/HuggingFaceLanguageModel.java
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/client/EmbeddingRequest.java
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/client/HuggingFaceClient.java
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/client/Options.java
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/client/Parameters.java
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/client/TextGenerationRequest.java
  langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/client/TextGenerationResponse.java
  langchain4j-hugging-face/src/test/java/dev/langchain4j/model/huggingface/HuggingFaceChatModelIT.java
  langchain4j-hugging-face/src/test/java/dev/langchain4j/model/huggingface/HuggingFaceEmbeddingModelIT.java
  langchain4j-hugging-face/src/test/java/dev/langchain4j/model/huggingface/HuggingFaceLanguageModelIT.java
Labels: P2

#1739 Azure OpenAI: Migrate from Gson to Jackson
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiTokenizer.java
Labels: Azure

#1723 Allow user to modify text key
  langchain4j-weaviate/src/main/java/dev/langchain4j/store/embedding/weaviate/WeaviateEmbeddingStore.java
Labels: P2

#1726 Added apiCallTimeout param for Bedrock and it fixes langchain4j/langc…
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockStreamingChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractSharedBedrockChatModel.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelIT.java
Labels: P2

#1697 Migrate Ollama from gson to jackson
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaJsonUtils.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaMessagesUtils.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaApiIT.java
Labels: P2

#1752 Added capability to set custom headers to Azure OpenAI model's builders
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiImageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelperTest.java
Labels: Azure

#1646 feat: Metadata filtering Qdrant
  CONTRIBUTING.md
  langchain4j-qdrant/pom.xml
  langchain4j-qdrant/src/main/java/dev/langchain4j/store/embedding/qdrant/ObjectFactory.java
  langchain4j-qdrant/src/main/java/dev/langchain4j/store/embedding/qdrant/QdrantEmbeddingStore.java
  langchain4j-qdrant/src/main/java/dev/langchain4j/store/embedding/qdrant/QdrantFilterConverter.java
  langchain4j-qdrant/src/main/java/dev/langchain4j/store/embedding/qdrant/ValueMapFactory.java
  langchain4j-qdrant/src/test/java/dev/langchain4j/store/embedding/qdrant/QdrantEmbeddingStoreIT.java
  langchain4j-qdrant/src/test/java/dev/langchain4j/store/embedding/qdrant/QdrantFilterConverterTest.java
Labels: P2

#1771 modified: docs/docs/integrations/language-models/google-ai-gemini.m…
  docs/docs/integrations/language-models/google-ai-gemini.md
Labels: Gemini

#1741 Google AI Gemini — support for Enum structured output
  docs/docs/integrations/language-models/google-ai-gemini.md
  docs/docs/integrations/language-models/index.md
  docs/docs/tutorials/5-ai-services.md
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelListenerIT.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/ResponseFormat.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/ChatModelListenerIT.java
  langchain4j-google-ai-gemini/pom.xml
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GeminiMode.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GeminiService.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModel.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiAiServicesWithJsonSchemaIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelListenerIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelListenerIT.java
  langchain4j-parent/pom.xml
  langchain4j-vertex-ai-gemini/pom.xml
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModel.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModel.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModelIT.java
  langchain4j-vertex-ai/pom.xml
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingModel.java
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingModelName.java
  langchain4j-vertex-ai/src/test/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingModelIT.java
  langchain4j-vertex-ai/src/test/java/dev/langchain4j/model/vertexai/VertexAiImageModelIT.java
  langchain4j/pom.xml
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesJsonSchemaIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithJsonSchemaIT.java
  langchain4j/src/test/java/dev/langchain4j/service/OpenAiAiServicesWithJsonSchemaIT.java
Labels: P2, Azure, Gemini

#1783 Bump com.azure:azure-identity from 1.13.2 to 1.13.3
  langchain4j-parent/pom.xml
Labels: Azure

#1779 feat(Vertex AI Gemini) — listener support (streaming and non streaming)
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/ChatModelListenerIT.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/StreamingChatModelListenerIT.java
  langchain4j-vertex-ai-gemini/pom.xml
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/FunctionCallHelper.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModel.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModel.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModelListenerIT.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModelListenerIT.java
Labels: P2, Gemini

#1778 fix Ollama call tool many times
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaMessagesUtils.java
Labels: P2

#1781 [BUG] ToolSpecifications misses object properties when object appears…
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolSpecifications.java
  langchain4j-core/src/test/java/dev/langchain4j/agent/tool/ToolSpecificationsTest.java
Labels: P2

#1755 [FEAT] Add Function Calling to Amazon Bedrock integration
  docs/docs/integrations/language-models/index.md
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicContent.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModelResponse.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAntropicToolSpecification.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelIT.java
  langchain4j/pom.xml
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java
Labels: P2

#1650 Add langchain4j-tablestore Integration: TablestoreEmbeddingStore/TablestoreChatMemoryStore
  docs/docs/integrations/embedding-stores/index.md
  docs/docs/integrations/embedding-stores/tablestore.md
  langchain4j-bom/pom.xml
  langchain4j-tablestore/pom.xml
  langchain4j-tablestore/src/main/java/dev/langchain4j/store/embedding/tablestore/IsTextMatch.java
  langchain4j-tablestore/src/main/java/dev/langchain4j/store/embedding/tablestore/IsTextMatchPhrase.java
  langchain4j-tablestore/src/main/java/dev/langchain4j/store/embedding/tablestore/TablestoreEmbeddingStore.java
  langchain4j-tablestore/src/main/java/dev/langchain4j/store/embedding/tablestore/TablestoreMetadataFilterMapper.java
  langchain4j-tablestore/src/main/java/dev/langchain4j/store/embedding/tablestore/TablestoreUtils.java
  langchain4j-tablestore/src/main/java/dev/langchain4j/store/memory/chat/tablestore/TablestoreChatMemoryStore.java
  langchain4j-tablestore/src/test/java/dev/langchain4j/store/embedding/tablestore/TablestoreEmbeddingStoreExampleIT.java
  langchain4j-tablestore/src/test/java/dev/langchain4j/store/embedding/tablestore/TablestoreEmbeddingStoreIT.java
  langchain4j-tablestore/src/test/java/dev/langchain4j/store/embedding/tablestore/TablestoreEmbeddingStoreRemovalIT.java
  langchain4j-tablestore/src/test/java/dev/langchain4j/store/embedding/tablestore/TablestoreEmbeddingStoreTest.java
  langchain4j-tablestore/src/test/java/dev/langchain4j/store/memory/chat/tablestore/TablestoreChatMemoryStoreIT.java
  langchain4j-tablestore/src/test/resources/logback-test.xml
  pom.xml
Labels: P3

#1796 Updated documentation for the Google Cloud Vertex AI embedding models and added new parameters (auto truncation and output dimensionality)
  docs/docs/integrations/embedding-models/google-vertex-ai.md
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingModel.java
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingParameters.java
  langchain4j-vertex-ai/src/test/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingModelIT.java
Labels: Gemini

#1793 Bumps com.azure:azure-storage-common from 12.26.1 to 12.27.0.
  langchain4j-parent/pom.xml
Labels: Azure

#1794 Bumps com.azure:azure-storage-blob from 12.27.1 to 12.28.0.
  langchain4j-parent/pom.xml
Labels: Azure

#1791 Added ChatModelListener in anthropic model
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/InternalAnthropicHelper.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicChatModelListenerIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModelListenerIT.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/StreamingChatModelListenerIT.java
Labels: P2

#1769 add scoring onnx
  docs/docs/integrations/scoring-reranking-models/in-process.md
  langchain4j-bom/pom.xml
  langchain4j-onnx-scoring/pom.xml
  langchain4j-onnx-scoring/src/main/java/dev/langchain4j/model/scoring/onnx/AbstractInProcessScoringModel.java
  langchain4j-onnx-scoring/src/main/java/dev/langchain4j/model/scoring/onnx/OnnxScoringBertCrossEncoder.java
  langchain4j-onnx-scoring/src/main/java/dev/langchain4j/model/scoring/onnx/OnnxScoringModel.java
  langchain4j-onnx-scoring/src/main/test/java/dev/langchain4j/model/scoring/onnx/OnnxScoringModelIT.java
  pom.xml
Labels: P2

#1795 FEATURE: Anthropic streaming with tools
  docs/docs/integrations/language-models/anthropic.md
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicContent.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicContentBlockType.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicCreateMessageRequest.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicDelta.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicToolChoice.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicToolChoiceType.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicToolExecutionRequestBuilder.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/DefaultAnthropicClient.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/mapper/AnthropicMapper.java
  langchain4j-anthropic/src/main/resources/META-INF/native-image/dev.langchain4j/langchain4j-anthropic/reflect-config.json
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModelIT.java
Labels: P2

#1802 fix(Google AI Gemini) — Fixed wrong mapping between function execution requests and function execution responses.
  docs/docs/integrations/document-loaders/google-cloud-storage.md
  document-loaders/langchain4j-document-loader-google-cloud-storage/pom.xml
  document-loaders/langchain4j-document-loader-google-cloud-storage/src/main/java/dev/langchain4j/data/document/loader/gcs/GoogleCloudStorageDocumentLoader.java
  document-loaders/langchain4j-document-loader-google-cloud-storage/src/main/java/dev/langchain4j/data/document/source/GcsSource.java
  document-loaders/langchain4j-document-loader-google-cloud-storage/src/test/java/dev/langchain4j/data/document/loader/gcs/GoogleCloudStorageDocumentLoaderIT.java
  langchain4j-bom/pom.xml
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/PartsAndContentsMapper.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModelIT.java
  pom.xml
Labels: P2, Gemini

#1820 New ScoringModel for Google Cloud Vertex AI Ranking API
  docs/docs/integrations/scoring-reranking-models/3-vertex-ai-ranking.md
  langchain4j-vertex-ai/pom.xml
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiScoringModel.java
  langchain4j-vertex-ai/src/test/java/dev/langchain4j/model/vertexai/VertexAiScoringModelIT.java
Labels: Gemini

#1816 Integration with Voyage
  docs/docs/integrations/embedding-models/voyage-ai.md
  docs/docs/integrations/scoring-reranking-models/3-voyage-ai.md
  langchain4j-bom/pom.xml
  langchain4j-voyage-ai/pom.xml
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/EmbeddingRequest.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/EmbeddingResponse.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/RequestLoggingInterceptor.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/RerankRequest.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/RerankResponse.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/ResponseLoggingInterceptor.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/TokenUsage.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/VoyageAiApi.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/VoyageAiClient.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/VoyageAiEmbeddingDeserializer.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/VoyageAiEmbeddingModel.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/VoyageAiEmbeddingModelName.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/VoyageAiJsonUtils.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/VoyageAiScoringModel.java
  langchain4j-voyage-ai/src/main/java/dev/langchain4j/model/voyageai/VoyageAiScoringModelName.java
  langchain4j-voyage-ai/src/test/java/dev/langchain4j/model/voyageai/VoyageAiEmbeddingDeserializerTest.java
  langchain4j-voyage-ai/src/test/java/dev/langchain4j/model/voyageai/VoyageAiEmbeddingModelIT.java
  langchain4j-voyage-ai/src/test/java/dev/langchain4j/model/voyageai/VoyageAiScoringModelIT.java
  pom.xml
Labels: P2, P3

#1823 Flaky tests
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModelIT.java
Labels: Gemini

#1807 Support for GitHub Models using the Azure AI Inference API
  docs/docs/integrations/language-models/github-models.md
  docs/docs/integrations/language-models/google-ai-gemini.md
  docs/docs/integrations/language-models/google-palm.md
  docs/docs/integrations/language-models/google-vertex-ai-gemini.md
  docs/docs/integrations/language-models/hugging-face.md
  docs/docs/integrations/language-models/index.md
  docs/docs/integrations/language-models/jlama.md
  docs/docs/integrations/language-models/local-ai.md
  docs/docs/integrations/language-models/mistral-ai.md
  docs/docs/integrations/language-models/ollama.md
  docs/docs/integrations/language-models/open-ai.md
  docs/docs/integrations/language-models/qianfan.md
  docs/docs/integrations/language-models/workers-ai.md
  docs/docs/integrations/language-models/zhipu-ai.md
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-github-models/pom.xml
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/GitHubModelsChatModel.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/GitHubModelsChatModelName.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/GitHubModelsEmbeddingModel.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/GitHubModelsEmbeddingModelName.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/GitHubModelsStreamingChatModel.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/GitHubModelsStreamingResponseBuilder.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/InternalGitHubModelHelper.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/spi/GitHubModelsChatModelBuilderFactory.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/spi/GitHubModelsEmbeddingModelBuilderFactory.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/spi/GitHubModelsStreamingChatModelBuilderFactory.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsChatModelIT.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsChatModelListenerIT.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsEmbeddingModelIT.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsStreamingChatModelIT.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsStreamingChatModelListenerIT.java
  langchain4j-github-models/src/test/resources/log4j2.xml
  pom.xml
Labels: P2, Azure
