Repository langchain4j/langchain4j, pull requests merged in 2024-07, with the labels that each got.

#1387 Bump com.azure:azure-search-documents from 11.6.5 to 11.6.6
  langchain4j-parent/pom.xml
Labels: Azure

#1364 AI Services: added an option to configure tools programmatically
  docs/docs/tutorials/6-tools.md
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/Tool.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolExecutionRequest.java
  langchain4j/src/main/java/dev/langchain4j/agent/tool/ToolExecutor.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java
Labels: P2

#1396 Adding Azure CLI script to deploy the Azure AI Search resources
  langchain4j-azure-ai-search/src/test/script/deploy-azure-ai-search.sh
Labels: Azure

#1291 [Feature] Support Metadata filtering with Azure AI Search
  docs/docs/integrations/embedding-stores/index.md
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetriever.java
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchFilterMapper.java
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/rag/content/retriever/azure/search/DefaultAzureAiSearchFilterMapper.java
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStore.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverTest.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/DefaultAzureAiSearchFilterMapperTest.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreTest.java
Labels: P2, Azure

#1278 Gemini updates
  docs/docs/tutorials/5-ai-services.md
  langchain4j-vertex-ai-gemini/pom.xml
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/ContentsMapper.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/HarmCategory.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/PartsMapper.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/ResponseGrounding.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/SafetySettingsMapper.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/SafetyThreshold.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/SchemaHelper.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/ToolCallingMode.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModel.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModel.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/ContentsMapperTest.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/SchemaHelperTest.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/resources/tinylog.properties
  langchain4j-vertex-ai/pom.xml
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingModel.java
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiImageModel.java
  langchain4j-vertex-ai/src/test/java/dev/langchain4j/model/vertexai/VertexAiImageModelIT.java
Labels: P2, Azure, Gemini

#1401 Bump com.azure:azure-ai-openai from 1.0.0-beta.8 to 1.0.0-beta.10
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAIResponsibleAIIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiImageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModelIT.java
  langchain4j-azure-open-ai/src/test/script/deploy-azure-openai-models.sh
  langchain4j-parent/pom.xml
Labels: Azure

#1431 [Doc] Refactor the Azure documentation
  docs/docs/integrations/embedding-models/azure-open-ai.md
  docs/docs/integrations/image-models/azure-dall-e.md
  docs/docs/integrations/language-models/azure-open-ai.md
Labels: Azure

#1435 Add Creating AzureOpenAiChatModel with Azure Credentials to the doc
  docs/docs/integrations/language-models/azure-open-ai.md
Labels: Azure

#1443 Update the Vertex AI and Gemini SDK libraries
  langchain4j-vertex-ai-gemini/pom.xml
  langchain4j-vertex-ai/pom.xml
Labels: Gemini

#1389 #725: PR 1 / 4: Addresses `EnumOutputParser` not being called
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultOutputParserFactory.java
  langchain4j/src/main/java/dev/langchain4j/service/OutputParserFactory.java
  langchain4j/src/main/java/dev/langchain4j/service/ServiceOutputParser.java
  langchain4j/src/test/java/dev/langchain4j/service/ServiceOutputParserTest.java
Labels: P2

#1398 #725: PR 3 / 4: Make enum values work with @Description annotation
  langchain4j/src/main/java/dev/langchain4j/model/output/EnumOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/service/ServiceOutputParser.java
  langchain4j/src/test/java/dev/langchain4j/model/output/OutputParserTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesIT.java
  langchain4j/src/test/java/dev/langchain4j/service/ServiceOutputParserTest.java
Labels: P2

#1450 Fix a enum serialization issue leading to stackoverflow when creating schemas from classes
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/SchemaHelper.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/SchemaHelperTest.java
Labels: Gemini

#1384 Feat(#1383): mutualise EmbeddingMatches handling
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetriever.java
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverIT.java
Labels: P2, Azure

#1358 [FEATURE] Add RedisChatMemoryStore implementation
  langchain4j-redis/src/main/java/dev/langchain4j/store/memory/chat/redis/RedisChatMemoryStore.java
  langchain4j-redis/src/main/java/dev/langchain4j/store/memory/chat/redis/RedisChatMemoryStoreException.java
  langchain4j-redis/src/test/java/dev/langchain4j/store/memory/chat/redis/RedisChatMemoryStoreIT.java
Labels: P2, P3

#1457 [Feature] Implement embedding removal methods for Chroma embedding
  langchain4j-chroma/pom.xml
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/AddEmbeddingsRequest.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaApi.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaClient.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStore.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaMetadataFilterMapper.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaRequestLoggingInterceptor.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaResponseLoggingInterceptor.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/Collection.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/CreateCollectionRequest.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/DeleteEmbeddingsRequest.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/QueryResponse.java
  langchain4j-chroma/src/test/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStoreIT.java
  langchain4j-chroma/src/test/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStoreRemovalIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithRemovalIT.java
Labels: P2

#1072 Migrate ollama to jackson
  langchain4j-ollama/pom.xml
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/ChatRequest.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/ChatResponse.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/CompletionRequest.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/CompletionResponse.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/EmbeddingRequest.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/EmbeddingResponse.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/Message.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/ModelsListResponse.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaMessagesUtils.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModelCard.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModelDetails.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/Options.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/Role.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/ShowModelInformationRequest.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaStreamingChatModelIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaStreamingLanguageModelIT.java
Labels: P2

#1456 Fix ollama client missing path issue
  langchain4j-ollama/pom.xml
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaApi.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaApiIT.java
  langchain4j-parent/pom.xml
Labels: P2

#1410 #725: PR 4 / 4: Make it possible to return list of enum values annotated with @Description annotation
  langchain4j/src/main/java/dev/langchain4j/model/output/CollectionOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/model/output/EnumCollectionOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/model/output/EnumListOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/model/output/EnumOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/model/output/EnumSetOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/model/output/StringListOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/model/output/StringSetOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultOutputParserFactory.java
  langchain4j/src/main/java/dev/langchain4j/service/OutputParserFactory.java
  langchain4j/src/main/java/dev/langchain4j/service/ServiceOutputParser.java
  langchain4j/src/main/java/dev/langchain4j/service/TypeUtils.java
  langchain4j/src/test/java/dev/langchain4j/model/output/EnumOutputParserTest.java
  langchain4j/src/test/java/dev/langchain4j/model/output/EnumSetOutputParserTest.java
  langchain4j/src/test/java/dev/langchain4j/model/output/OutputParserTest.java
  langchain4j/src/test/java/dev/langchain4j/model/output/StringSetOutputParserTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesIT.java
  langchain4j/src/test/java/dev/langchain4j/service/ServiceOutputParserTest.java
  langchain4j/src/test/java/dev/langchain4j/service/TypeUtilsTest.java
Labels: P2

#1478 Bump com.azure:azure-identity from 1.13.0 to 1.13.1
  langchain4j-parent/pom.xml
Labels: Azure

#1499 Bump com.knuddels:jtokkit from 1.0.0 to 1.1.0
  langchain4j-parent/pom.xml
Labels: P2

#1479 DefaultRetrievalAugmentor: process in the same thread when single query and single retriever, otherwise use executor and cache threads for 1 second
  docs/docs/integrations/embedding-models/1-in-process.md
  docs/docs/tutorials/5-ai-services.md
  docs/docs/tutorials/7-rag.md
  langchain4j-core/src/main/java/dev/langchain4j/rag/DefaultRetrievalAugmentor.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/DefaultRetrievalAugmentorTest.java
Labels: P1, P2

#1487 Adding support for Amazon Bedrock Titan Embedding Model V2 (amazon.titan-embed-text-v2:0)
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockTitanEmbeddingModel.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockEmbeddingIT.java
Labels: P2

#1464 Adding support to audio, video, PDF file inputs for multimodal models
  docs/docs/integrations/embedding-models/google-vertex-ai.md
  docs/docs/integrations/language-models/google-gemini.md
  docs/docs/integrations/language-models/index.md
  langchain4j-core/src/main/java/dev/langchain4j/data/audio/Audio.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/AudioContent.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/ContentType.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/GsonChatMessageAdapter.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/PdfFileContent.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/UserMessage.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/VideoContent.java
  langchain4j-core/src/main/java/dev/langchain4j/data/pdf/PdfFile.java
  langchain4j-core/src/main/java/dev/langchain4j/data/video/Video.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/Utils.java
  langchain4j-core/src/test/java/dev/langchain4j/data/message/AudioContentTest.java
  langchain4j-core/src/test/java/dev/langchain4j/data/message/ChatMessageSerializerTest.java
  langchain4j-core/src/test/java/dev/langchain4j/data/message/PdfFileContentTest.java
  langchain4j-core/src/test/java/dev/langchain4j/data/message/VideoContentTest.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/PartsMapper.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/PartsMapperTest.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/resources/fingers.mp4
  langchain4j-vertex-ai-gemini/src/test/resources/gemini-doc-snapshot.pdf
Labels: P2, Gemini

#1355 feat: ✨ add OVHcloud embedding models
  docs/docs/integrations/embedding-models/ovh-ai.md
  langchain4j-bom/pom.xml
  langchain4j-ovh-ai/pom.xml
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/OvhAiEmbeddingModel.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/internal/api/EmbeddingRequest.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/internal/api/EmbeddingResponse.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/internal/api/OvhAiApi.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/internal/client/DefaultOvhAiClient.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/internal/client/OvhAiClient.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/internal/client/OvhAiClientBuilderFactory.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/internal/client/RequestLoggingInterceptor.java
  langchain4j-ovh-ai/src/main/java/dev/langchain4j/model/ovhai/internal/client/ResponseLoggingInterceptor.java
  langchain4j-ovh-ai/src/test/java/dev/langchain4j/model/ovhai/OvhAiEmbeddingModelIT.java
  pom.xml
Labels: P3
