Repository langchain4j/langchain4j, pull requests merged in 2024-12, with the labels that each got.

#2217 Change the safetySetting builder to support map of harmCategory and HarmBlockThreshold and toolConfig to support geminiMode and ListofFunctionNames
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiStreamingChatModel.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiStreamingChatModelIT.java
Labels: P2, P3, Gemini

#2153 #2109 Add Spotless Maven Plugin
  .github/workflows/receive-pr.yml
  CONTRIBUTING.md
  Makefile
  code-execution-engines/langchain4j-code-execution-engine-judge0/pom.xml
  document-loaders/langchain4j-document-loader-amazon-s3/pom.xml
  document-loaders/langchain4j-document-loader-azure-storage-blob/pom.xml
  document-loaders/langchain4j-document-loader-github/pom.xml
  document-loaders/langchain4j-document-loader-google-cloud-storage/pom.xml
  document-loaders/langchain4j-document-loader-selenium/pom.xml
  document-loaders/langchain4j-document-loader-tencent-cos/pom.xml
  document-parsers/langchain4j-document-parser-apache-pdfbox/pom.xml
  document-parsers/langchain4j-document-parser-apache-poi/pom.xml
  document-parsers/langchain4j-document-parser-apache-tika/pom.xml
  document-transformers/langchain4j-document-transformer-jsoup/pom.xml
  embedding-store-filter-parsers/langchain4j-embedding-store-filter-parser-sql/pom.xml
  experimental/langchain4j-experimental-sql/pom.xml
  langchain4j-anthropic/pom.xml
  langchain4j-chroma/pom.xml
  langchain4j-cohere/pom.xml
  langchain4j-hugging-face/pom.xml
  langchain4j-jina/pom.xml
  langchain4j-jlama/pom.xml
  langchain4j-mistral-ai/pom.xml
  langchain4j-nomic/pom.xml
  langchain4j-ollama/pom.xml
  langchain4j-open-ai/pom.xml
  langchain4j-ovh-ai/pom.xml
  langchain4j-parent/pom.xml
  langchain4j-pgvector/pom.xml
  langchain4j-vespa/pom.xml
  langchain4j-voyage-ai/pom.xml
  langchain4j-workers-ai/pom.xml
  pom.xml
  web-search-engines/langchain4j-web-search-engine-google-custom/pom.xml
  web-search-engines/langchain4j-web-search-engine-searchapi/pom.xml
  web-search-engines/langchain4j-web-search-engine-tavily/pom.xml
Labels: P2, P3, Azure

#2195 Add jspecify nullability annotations
  langchain4j-core/pom.xml
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/response/ChatResponse.java
  langchain4j-core/src/main/java/dev/langchain4j/model/output/Response.java
  langchain4j-parent/pom.xml
Labels: P3

#2181 Jlama: add tool support to streaming chat models. closes #2115
  docs/docs/integrations/language-models/index.md
  langchain4j-jlama/pom.xml
  langchain4j-jlama/src/main/java/dev/langchain4j/model/jlama/JlamaChatModel.java
  langchain4j-jlama/src/main/java/dev/langchain4j/model/jlama/JlamaStreamingChatModel.java
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaStreamingChatModelToolsIT.java
Labels: P2, P3

#2221 #1780 Better dpendency managenemt with BOMs
  code-execution-engines/langchain4j-code-execution-engine-judge0/pom.xml
  langchain4j-chroma/pom.xml
  langchain4j-cohere/pom.xml
  langchain4j-hugging-face/pom.xml
  langchain4j-mistral-ai/pom.xml
  langchain4j-nomic/pom.xml
  langchain4j-ollama/pom.xml
  langchain4j-parent/pom.xml
  langchain4j-vespa/pom.xml
  langchain4j-voyage-ai/pom.xml
  langchain4j-workers-ai/pom.xml
  web-search-engines/langchain4j-web-search-engine-searchapi/pom.xml
  web-search-engines/langchain4j-web-search-engine-tavily/pom.xml
Labels: P2, P3, Dependencies

#2156 EmbeddingStore: implement addAll(ids, embeddings, segments)
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java
  langchain4j-azure-cosmos-mongo-vcore/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/mongo/vcore/AzureCosmosDbMongoVCoreEmbeddingStore.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDbNoSqlEmbeddingStore.java
  langchain4j-cassandra/src/main/java/dev/langchain4j/store/embedding/astradb/AstraDbEmbeddingStore.java
  langchain4j-cassandra/src/main/java/dev/langchain4j/store/embedding/cassandra/CassandraEmbeddingStore.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStore.java
  langchain4j-coherence/src/main/java/dev/langchain4j/store/embedding/coherence/CoherenceEmbeddingStore.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/EmbeddingStore.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreTest.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithoutMetadataIT.java
  langchain4j-couchbase/src/main/java/dev/langchain4j/store/embedding/couchbase/CouchbaseEmbeddingStore.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStore.java
  langchain4j-infinispan/src/main/java/dev/langchain4j/store/embedding/infinispan/InfinispanEmbeddingStore.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStore.java
  langchain4j-mongodb-atlas/src/main/java/dev/langchain4j/store/embedding/mongodb/MongoDbEmbeddingStore.java
  langchain4j-neo4j/src/main/java/dev/langchain4j/store/embedding/neo4j/Neo4jEmbeddingStore.java
  langchain4j-opensearch/src/main/java/dev/langchain4j/store/embedding/opensearch/OpenSearchEmbeddingStore.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/OracleEmbeddingStore.java
  langchain4j-pgvector/src/main/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStore.java
  langchain4j-pgvector/src/test/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStore029.java
  langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStore.java
  langchain4j-qdrant/src/main/java/dev/langchain4j/store/embedding/qdrant/QdrantEmbeddingStore.java
  langchain4j-redis/src/main/java/dev/langchain4j/store/embedding/redis/RedisEmbeddingStore.java
  langchain4j-tablestore/src/main/java/dev/langchain4j/store/embedding/tablestore/TablestoreEmbeddingStore.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaEmbeddingStore.java
  langchain4j-weaviate/src/main/java/dev/langchain4j/store/embedding/weaviate/WeaviateEmbeddingStore.java
  langchain4j/src/main/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStore.java
Labels: P2, Azure

#2240 Initial implementation of the MCP client and tool provider
  docs/docs/tutorials/mcp.md
  langchain4j-bom/pom.xml
  langchain4j-mcp/pom.xml
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/McpToolProvider.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/DefaultMcpClient.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/McpClient.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/ToolExecutionHelper.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/ToolSpecificationHelper.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/ClientMethod.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/InitializeParams.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/McpCallToolRequest.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/McpClientMessage.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/McpInitializeRequest.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/McpListToolsRequest.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/McpTransport.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/HttpMcpTransport.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/McpRequestLoggingInterceptor.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/SseEventListener.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/stdio/ProcessIOHandler.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/stdio/ProcessStderrHandler.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/stdio/StdioMcpTransport.java
  langchain4j-mcp/src/test/java/dev/langchain4j/mcp/client/ToolSpecificationHelperTest.java
  langchain4j-mcp/src/test/java/dev/langchain4j/mcp/client/transport/http/McpHttpTransportTest.java
  langchain4j-mcp/src/test/resources/everything/README.md
  langchain4j-mcp/src/test/resources/everything/dist/everything.js
  langchain4j-mcp/src/test/resources/everything/dist/index.js
  langchain4j-mcp/src/test/resources/everything/dist/sse.js
  langchain4j-mcp/src/test/resources/everything/everything.ts
  langchain4j-mcp/src/test/resources/everything/index.ts
  langchain4j-mcp/src/test/resources/everything/package.json
  langchain4j-mcp/src/test/resources/everything/sse.ts
  langchain4j-mcp/src/test/resources/everything/tsconfig.json
  pom.xml
Labels: P2

#2267 Properly receive the MCP POST URL from the MCP server
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/HttpMcpTransport.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/SseEventListener.java
  langchain4j-mcp/src/test/java/dev/langchain4j/mcp/client/transport/http/McpHttpTransportTest.java
Labels: P2

#2187 Update pgvector.md
  docs/docs/integrations/embedding-stores/pgvector.md
Labels: P2, P3

#2265 Configurable timeout for tool executions over MCP
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/DefaultMcpClient.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/CancellationNotification.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/ClientMethod.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/McpClientMessage.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/McpTransport.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/HttpMcpTransport.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/SseEventListener.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/stdio/StdioMcpTransport.java
  langchain4j-mcp/src/test/java/dev/langchain4j/mcp/client/transport/http/McpHttpTransportTest.java
Labels: P2

#2248 draft: fix OpenAiEmbeddingModel request text array overflow
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiEmbeddingModel.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiEmbeddingModelIT.java
Labels: P2

#2210 Ollama: support tools in streaming mode
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaMessagesUtils.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingResponseBuilder.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaToolChatModelIT.java
Labels: P2, P3

#1982 Upgrade to Azure OpenAI SDK 1.0.0-beta.12 + Structured Outputs support
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModelName.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiImageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiTokenizer.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiAiServicesWithJsonSchemaIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenizerIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenizerTest.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelperTest.java
  langchain4j-azure-open-ai/src/test/script/deploy-azure-openai-models.sh
  langchain4j-core/src/main/java/dev/langchain4j/internal/Utils.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonSchemaElementHelper.java
  langchain4j-parent/pom.xml
Labels: P2, Azure

#2307 Simple wording issue in the documentation
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
Labels: Azure

#2222 [FEATURE] Added metadata (score and embeddedId) for Content
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetriever.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetrieverTest.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/ValidationUtils.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/Content.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/ContentMetadata.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/aggregator/ReRankingContentAggregator.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/retriever/EmbeddingStoreContentRetriever.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/ContentTest.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/aggregator/ReRankingContentAggregatorTest.java
Labels: P2, P3, Azure, RAG

#2208 Apache Tika Document Parser: Fix failure due to XPathFactoryConfigurationException
  document-parsers/langchain4j-document-parser-apache-tika/pom.xml
  document-parsers/langchain4j-document-parser-apache-tika/src/test/resources/test-file.pptx
  langchain4j-easy-rag/pom.xml
Labels: P2, P3

#2312 Fix #1875: Azure OpenAI: propagate all exceptions in chat models
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiResponsibleAiIT.java
Labels: Azure, Breaking Change

#2203 update spring-boot-integration.md for [add AiServiceRegisteredEvent]
  docs/docs/tutorials/spring-boot-integration.md
Labels: P2, P3

#2320 [Google AI Gemini] Append newlines between text parts.
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/PartsAndContentsMapper.java
Labels: Gemini
