Repository langchain4j/langchain4j, pull requests merged in 2024-06, with the labels that each got.

#740 Fix @UserMessage does not work
  langchain4j-core/src/main/java/dev/langchain4j/model/input/Prompt.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/DefaultRetrievalAugmentor.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/injector/DefaultContentInjector.java
  langchain4j-core/src/test/java/dev/langchain4j/model/input/PromptTest.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/injector/DefaultContentInjectorTest.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
Labels: P3

#726 Allow HtmlTextExtractor to extract relative links from document
  langchain4j/src/main/java/dev/langchain4j/data/document/transformer/HtmlTextExtractor.java
  langchain4j/src/test/java/dev/langchain4j/data/document/transformer/HtmlTextExtractorTest.java
Labels: P3

#1229 Updated model listener API to be more integration friendly
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelErrorContext.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelListener.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelRequest.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelRequestContext.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelResponse.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelResponseContext.java
  langchain4j-core/src/main/java/dev/langchain4j/model/listener/ModelListener.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/InternalOpenAiHelper.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
Labels: P2

#1148 Implementation of a lambda based streaming response handler
  langchain4j-core/src/main/java/dev/langchain4j/model/LambdaStreamingResponseHandler.java
  langchain4j-core/src/test/java/dev/langchain4j/model/LambdaStreamingResponseHandlerTest.java
Labels: P2

#1222 Add a Tokenizer to Azure OpenAI
  langchain4j-azure-open-ai/pom.xml
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModelName.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModelName.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiImageModelName.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModelName.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiTokenizer.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAIResponsibleAIIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenizerIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenizerTest.java
  langchain4j-azure-open-ai/src/test/script/deploy-azure-openai-models.sh
Labels: P2

#1172 Implement embedding removal methods for Milvus embedding store
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/EmbeddingStore.java
  langchain4j-milvus/pom.xml
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/CollectionOperationsExecutor.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/CollectionRequestBuilder.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStore.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusMetadataFilterMapper.java
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreCloudIT.java
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreIT.java
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreRemoveIT.java
  langchain4j-parent/pom.xml
Labels: P2

#1259 AzureAiSearchEmbeddingStore with index creation
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreIT.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/store/embedding/azure/search/AzureAiSearchEmbeddingStoreTest.java
Labels: P2

#1197 fix issue 940 - Anthropic API requires 1st message to be a UserMessage
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/sanitizer/MessageSanitizer.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/internal/sanitizer/MessageSanitizerTest.java
Labels: P2

#1198 [FEATURE] Implement Elasticsearch embedding removal methods
  langchain4j-elasticsearch/pom.xml
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStore.java
  langchain4j-elasticsearch/src/test/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStoreRemoveIT.java
Labels: P2

#1213 Fix deprecated methods
  document-loaders/langchain4j-document-loader-amazon-s3/src/test/java/dev/langchain4j/data/document/loader/amazon/s3/AmazonS3DocumentLoaderIT.java
  document-loaders/langchain4j-document-loader-azure-storage-blob/src/main/java/dev/langchain4j/data/document/source/azure/storage/blob/AzureBlobStorageSource.java
  document-loaders/langchain4j-document-loader-azure-storage-blob/src/test/java/dev/langchain4j/data/document/loader/azure/storage/blob/AzureBlobStorageDocumentLoaderIT.java
  document-loaders/langchain4j-document-loader-azure-storage-blob/src/test/java/dev/langchain4j/data/document/loader/azure/storage/blob/LocalAzureBlobStorageDocumentLoaderIT.java
  document-loaders/langchain4j-document-loader-github/src/main/java/dev/langchain4j/data/document/source/github/GitHubSource.java
  document-loaders/langchain4j-document-loader-github/src/test/java/dev/langchain4j/data/document/loader/github/GitHubDocumentLoaderIT.java
  document-loaders/langchain4j-document-loader-tencent-cos/src/test/java/dev/langchain4j/data/document/loader/tencent/cos/TencentCosDocumentLoaderIT.java
  document-parsers/langchain4j-document-parser-apache-pdfbox/src/test/java/dev/langchain4j/data/document/parser/apache/pdfbox/ApachePdfBoxDocumentParserTest.java
  document-parsers/langchain4j-document-parser-apache-poi/src/test/java/dev/langchain4j/data/document/parser/apache/poi/ApachePoiDocumentParserTest.java
  document-parsers/langchain4j-document-parser-apache-tika/src/test/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParserTest.java
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/embedding/cassandra/CassandraEmbeddingStoreIT.java
  langchain4j-core/src/main/java/dev/langchain4j/data/document/Document.java
  langchain4j-core/src/main/java/dev/langchain4j/web/search/WebSearchOrganicResult.java
  langchain4j-core/src/test/java/dev/langchain4j/data/document/DocumentLoaderTest.java
  langchain4j-core/src/test/java/dev/langchain4j/data/document/MetadataTest.java
  langchain4j-core/src/test/java/dev/langchain4j/data/segment/TextSegmentTest.java
  langchain4j-core/src/test/java/dev/langchain4j/data/segment/TextSegmentTransformerTest.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/injector/DefaultContentInjectorTest.java
  langchain4j-vertex-ai/src/test/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingModelIT.java
  langchain4j-weaviate/src/main/java/dev/langchain4j/store/embedding/weaviate/WeaviateEmbeddingStore.java
  langchain4j/src/main/java/dev/langchain4j/data/document/source/FileSystemSource.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/HierarchicalDocumentSplitter.java
  langchain4j/src/main/java/dev/langchain4j/data/document/transformer/HtmlTextExtractor.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/DocumentByParagraphSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/DocumentByRegexSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/DocumentBySentenceSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/transformer/HtmlTextExtractorTest.java
Labels: P3

#1262 Add support for Workers AI provider by CloudFlare
  langchain4j-workers-ai/pom.xml
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/WorkersAiChatModel.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/WorkersAiChatModelName.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/WorkersAiEmbeddingModel.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/WorkersAiEmbeddingModelName.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/WorkersAiImageModel.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/WorkersAiImageModelName.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/WorkersAiLanguageModel.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/AbstractWorkersAIModel.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/ApiResponse.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiApi.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiChatCompletionRequest.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiChatCompletionResponse.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiClient.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiEmbeddingRequest.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiEmbeddingResponse.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiImageGenerationRequest.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiImageGenerationResponse.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiTextCompletionRequest.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/client/WorkersAiTextCompletionResponse.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/spi/WorkersAiChatModelBuilderFactory.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/spi/WorkersAiEmbeddingModelBuilderFactory.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/spi/WorkersAiImageModelBuilderFactory.java
  langchain4j-workers-ai/src/main/java/dev/langchain4j/model/workersai/spi/WorkersAiLanguageModelBuilderFactory.java
  langchain4j-workers-ai/src/test/java/dev/langchain4j/model/workersai/WorkerAIChatModelIT.java
  langchain4j-workers-ai/src/test/java/dev/langchain4j/model/workersai/WorkerAIEmbeddingModelIT.java
  langchain4j-workers-ai/src/test/java/dev/langchain4j/model/workersai/WorkerAILanguageModelIT.java
  langchain4j-workers-ai/src/test/java/dev/langchain4j/model/workersai/WorkerAiImageModelIT.java
  pom.xml
Labels: P3

#1095 Fix 1079
  langchain4j-zhipu-ai/pom.xml
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/AssistantMessageTypeAdapter.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/AuthorizationInterceptor.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/DefaultZhipuAiHelper.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/Json.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/RequestLoggingInterceptor.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/ResponseLoggingInterceptor.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/ZhipuAiChatModel.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/ZhipuAiClient.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/ZhipuAiEmbeddingModel.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/ZhipuAiStreamingChatModel.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/AssistantMessage.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/ChatCompletionChoice.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/ChatCompletionRequest.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/ChatCompletionResponse.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/Delta.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/Function.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/FunctionCall.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/Parameters.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/Retrieval.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/Role.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/SystemMessage.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/Tool.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/ToolCall.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/ToolChoice.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/ToolChoiceMode.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/ToolMessage.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/ToolType.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/UserMessage.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/chat/WebSearch.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/embedding/Embedding.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/embedding/EmbeddingRequest.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/embedding/EmbeddingResponse.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/shared/ErrorResponse.java
  langchain4j-zhipu-ai/src/main/java/dev/langchain4j/model/zhipu/shared/Usage.java
  langchain4j-zhipu-ai/src/test/java/dev/langchain4j/model/zhipu/ZhipuAiChatModelIT.java
  langchain4j-zhipu-ai/src/test/java/dev/langchain4j/model/zhipu/ZhipuAiStreamingChatModelIT.java
Labels: P3

#1220 Implement remove methods for InMemoryEmbeddingStore
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithRemovalIT.java
  langchain4j-pgvector/src/test/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStoreRemoveIT.java
  langchain4j/src/main/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStore.java
  langchain4j/src/test/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStoreRemovalTest.java
Labels: P3

#1196 [FEATURE] Implement embedding removal methods for Weaviate embedding
  langchain4j-weaviate/src/main/java/dev/langchain4j/store/embedding/weaviate/WeaviateEmbeddingStore.java
  langchain4j-weaviate/src/test/java/dev/langchain4j/store/embedding/weaviate/LocalWeaviateEmbeddingStoreRemoveIT.java
Labels: P2

#1007 Issue 972: [FEATURE] Add name to dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever to improve logs
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/retriever/EmbeddingStoreContentRetriever.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/retriever/EmbeddingStoreContentRetrieverTest.java
Labels: P2

#1186 Qianfan: clear throw exception when call qianfan api has error code （…
  langchain4j-qianfan/src/main/java/dev/langchain4j/model/qianfan/client/QianfanApiException.java
  langchain4j-qianfan/src/main/java/dev/langchain4j/model/qianfan/client/QianfanClient.java
  langchain4j-qianfan/src/test/java/dev/langchain4j/model/qianfan/QianfanChatModelIT.java
Labels: P2

#1211 [FEATURE] Metadata UUID Support
  langchain4j-core/src/main/java/dev/langchain4j/data/document/Metadata.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/MetadataFilterBuilder.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/IsEqualTo.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/IsIn.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/IsNotEqualTo.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/IsNotIn.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/TypeChecker.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/UUIDComparator.java
  langchain4j-core/src/test/java/dev/langchain4j/data/document/MetadataTest.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithFilteringIT.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchMetadataFilterMapper.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusMetadataFilterMapper.java
  langchain4j-pgvector/src/main/java/dev/langchain4j/store/embedding/pgvector/PgVectorFilterMapper.java
  langchain4j-pgvector/src/test/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStoreWithColumnsFilteringIT.java
  langchain4j-weaviate/src/test/java/dev/langchain4j/store/embedding/weaviate/CloudWeaviateEmbeddingStoreIT.java
  langchain4j-weaviate/src/test/java/dev/langchain4j/store/embedding/weaviate/LocalGRPCWeaviateEmbeddingStoreIT.java
  langchain4j-weaviate/src/test/java/dev/langchain4j/store/embedding/weaviate/LocalWeaviateEmbeddingStoreIT.java
  langchain4j/src/main/java/dev/langchain4j/store/embedding/inmemory/GsonInMemoryEmbeddingStoreJsonCodec.java
Labels: P3

#1305 chroe: add ChatModelListener support for azure openai chat model and streaming chat model
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
Labels: P2, Azure

#708 Tools: support schema for custom POJO parameters
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/JsonSchemaProperty.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolSpecifications.java
  langchain4j-core/src/test/java/dev/langchain4j/agent/tool/ToolSpecificationsTest.java
  langchain4j/src/main/java/dev/langchain4j/agent/tool/DefaultToolExecutor.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java
Labels: P2

#1315 enable userAgentSuffix in azure open ai
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiImageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelperTest.java
Labels: Azure

#1280 Fix 1266 Allow using streaming AI Service with tools without memory
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceStreamingResponseHandler.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStream.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesWithToolsWithoutMemoryIT.java
Labels: P2

#1345 Bump com.azure:azure-identity from 1.12.2 to 1.13.0
  langchain4j-parent/pom.xml
Labels: Azure

#1354 Azure OpenAI: AzureOpenAiStreamingChatModel should work without Tokenizer (when using tools)
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
Labels: Azure

#1282 Fix AzureOpenAiStreamingChatModel constructor get or default new Tokenizer
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
Labels: Azure

#1352 [BUG-1339] - removed trailing commas from tool execution request argu…
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolExecutionRequestUtil.java
  langchain4j-core/src/test/java/dev/langchain4j/agent/tool/ToolExecutionRequestUtilTest.java
Labels: P2

#1370 [FEATURE] toolSpecificationFrom method support configuration of optional parameters
  docs/docs/tutorials/6-tools.md
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/P.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolSpecifications.java
  langchain4j-core/src/test/java/dev/langchain4j/agent/tool/ToolSpecificationsTest.java
Labels: P2
