Repository langchain4j/langchain4j, pull requests merged in 2025-03, with the labels that each got.

#2640 Kotlin extensions for DocumentLoader and DocumentParser
  langchain4j-core/pom.xml
  langchain4j-core/src/main/java/dev/langchain4j/data/document/Metadata.java
  langchain4j-core/src/main/kotlin/dev/langchain4j/data/document/DocumentLoaderExtensions.kt
  langchain4j-core/src/main/kotlin/dev/langchain4j/data/document/DocumentParserExtensions.kt
  langchain4j-core/src/test/kotlin/dev/langchain4j/data/document/DocumentParserExtensionsKtTest.kt
  langchain4j-core/src/test/kotlin/dev/langchain4j/data/document/MergeMetadataTest.kt
  langchain4j-parent/pom.xml
  langchain4j/pom.xml
  langchain4j/src/main/kotlin/dev/langchain4j/data/document/loader/FileSystemDocumentLoaderExtensions.kt
  langchain4j/src/test/kotlin/dev/langchain4j/data/document/loader/AsyncDocumentLoaderTest.kt
Labels: enhancement, Kotlin

#2666 Update azure-ai-inference from 1.0.0-beta.2 to 1.0.0-beta.4
  langchain4j-github-models/pom.xml
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/InternalGitHubModelHelper.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsChatModelIT.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsStreamingChatModelIT.java
Labels: Azure

#2668 Removed deprecated JsonSchemaProperty, ToolParameters and Tokenizer APIs
  docs/docs/integrations/language-models/google-vertex-ai-gemini.md
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/mapper/AnthropicMapper.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicMapperTest.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiTokenizer.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenizerIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenizerTest.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelperTest.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelWithConverseAPIIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelWithInvokeAPIIT.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/JsonSchemaProperty.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolParameters.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolSpecification.java
  langchain4j-core/src/main/java/dev/langchain4j/model/Tokenizer.java
  langchain4j-core/src/test/java/dev/langchain4j/agent/tool/JsonSchemaPropertyTest.java
  langchain4j-core/src/test/java/dev/langchain4j/agent/tool/ToolParametersTest.java
  langchain4j-core/src/test/java/dev/langchain4j/agent/tool/ToolSpecificationTest.java
  langchain4j-core/src/test/java/dev/langchain4j/agent/tool/ToolSpecificationsTest.java
  langchain4j-core/src/test/java/dev/langchain4j/model/ExampleTestTokenizer.java
  langchain4j-core/src/test/java/dev/langchain4j/model/TokenizerTest.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/ChatModelListenerIT.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/StreamingChatModelListenerIT.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/InternalGitHubModelHelper.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsChatModelIT.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsStreamingChatModelIT.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/FunctionMapper.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiTokenizer.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/FunctionMapperTest.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiTokenizerIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/common/GoogleAiGeminiChatModelIT.java
  langchain4j-jlama/src/main/java/dev/langchain4j/model/jlama/JlamaModel.java
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaChatModelToolsIT.java
  langchain4j-jlama/src/test/java/dev/langchain4j/model/jlama/JlamaStreamingChatModelToolsIT.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/mapper/MistralAiMapper.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiChatModelIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiStreamingChatModelIT.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaMessagesUtils.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaToolChatModelIT.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/InternalOpenAiHelper.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiTokenizer.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiTokenizerIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiTokenizerTest.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/FunctionCallHelper.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/FunctionCallHelperTest.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModelIT.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModelIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java
Labels: Breaking Change

#2670 Update Anthropic tests for error responses and parallelism
  langchain4j-anthropic/pom.xml
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicAiServicesWithToolsIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicChatModelErrorsTest.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicChatModelListenerIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModelListenerIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/common/AnthropicAiServiceIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/common/AnthropicChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/common/AnthropicStreamingAiServiceIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/common/AnthropicStreamingChatModelIT.java
  langchain4j-anthropic/src/test/resources/junit-platform.properties
  langchain4j-parent/pom.xml
Labels: Testing

#2678 Openai errors test
  langchain4j-open-ai/pom.xml
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelErrorsTest.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelWithJsonSchemaIT.java
  langchain4j-parent/pom.xml
Labels: Testing

#2702 Remove deprecated ChatModelRequest and ChatModelResponse
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/InternalAnthropicHelper.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockAnthropicMessageChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockMistralAiChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockStreamingChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractSharedBedrockChatModel.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelErrorContext.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelRequest.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelRequestContext.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelResponse.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/listener/ChatModelResponseContext.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/ChatModelListenerIT.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/StreamingChatModelListenerIT.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/GitHubModelsChatModel.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/GitHubModelsStreamingChatModel.java
  langchain4j-github-models/src/main/java/dev/langchain4j/model/github/InternalGitHubModelHelper.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/BaseGeminiChatModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiStreamingChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModelListenerUtils.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/VertexAiGeminiChatModel.java
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/VertexAiGeminiStreamingChatModel.java
Labels: Breaking Change

#2723 refactor-poms
  code-execution-engines/langchain4j-code-execution-engine-graalvm-polyglot/pom.xml
  code-execution-engines/langchain4j-code-execution-engine-judge0/pom.xml
  embedding-store-filter-parsers/langchain4j-embedding-store-filter-parser-sql/pom.xml
  http-clients/langchain4j-http-client-jdk/pom.xml
  langchain4j-anthropic/pom.xml
  langchain4j-azure-ai-search/pom.xml
  langchain4j-azure-cosmos-mongo-vcore/pom.xml
  langchain4j-azure-cosmos-nosql/pom.xml
  langchain4j-cassandra/pom.xml
  langchain4j-chroma/pom.xml
  langchain4j-cohere/pom.xml
  langchain4j-coherence/pom.xml
  langchain4j-core/pom.xml
  langchain4j-core/src/test/kotlin/dev/langchain4j/model/chat/request/ChatRequestExtensionsTest.kt
  langchain4j-couchbase/pom.xml
  langchain4j-easy-rag/pom.xml
  langchain4j-elasticsearch/pom.xml
  langchain4j-google-ai-gemini/pom.xml
  langchain4j-http-client/pom.xml
  langchain4j-infinispan/pom.xml
  langchain4j-jina/pom.xml
  langchain4j-local-ai/pom.xml
  langchain4j-mariadb/pom.xml
  langchain4j-mcp/pom.xml
  langchain4j-milvus/pom.xml
  langchain4j-mistral-ai/pom.xml
  langchain4j-mongodb-atlas/pom.xml
  langchain4j-neo4j/pom.xml
  langchain4j-nomic/pom.xml
  langchain4j-ollama/pom.xml
  langchain4j-open-ai-official/pom.xml
  langchain4j-open-ai/pom.xml
  langchain4j-opensearch/pom.xml
  langchain4j-oracle/pom.xml
  langchain4j-ovh-ai/pom.xml
  langchain4j-parent/pom.xml
  langchain4j-pgvector/pom.xml
  langchain4j-pinecone/pom.xml
  langchain4j-qdrant/pom.xml
  langchain4j-tablestore/pom.xml
  langchain4j-vertex-ai-gemini/pom.xml
  langchain4j-vespa/pom.xml
  langchain4j-voyage-ai/pom.xml
  langchain4j-weaviate/pom.xml
  langchain4j/pom.xml
  langchain4j/src/test/kotlin/dev/langchain4j/data/document/loader/AsyncDocumentLoaderTest.kt
  web-search-engines/langchain4j-web-search-engine-google-custom/pom.xml
Labels: Kotlin, Dependencies

#2750 Remove deprecated EmbeddingStore.findRelevant API
  docs/docs/integrations/embedding-models/jlama.md
  docs/docs/integrations/embedding-models/mistral-ai.md
  docs/docs/integrations/embedding-models/ovh-ai.md
  docs/docs/integrations/embedding-stores/couchbase.md
  langchain4j-azure-cosmos-mongo-vcore/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/mongo/vcore/AzureCosmosDbMongoVCoreEmbeddingStore.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDbNoSqlEmbeddingStore.java
  langchain4j-cassandra/src/main/java/dev/langchain4j/store/embedding/astradb/AstraDbEmbeddingStore.java
  langchain4j-cassandra/src/main/java/dev/langchain4j/store/embedding/cassandra/CassandraEmbeddingStore.java
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/embedding/cassandra/CassandraEmbeddingStoreIT.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStore.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/EmbeddingStore.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreTest.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithoutMetadataIT.java
  langchain4j-elasticsearch/src/main/java/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStore.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStore.java
  langchain4j-mongodb-atlas/src/test/java/dev/langchain4j/store/embedding/mongodb/MongoDbEmbeddingStoreMiscIT.java
  langchain4j-neo4j/src/test/java/dev/langchain4j/store/embedding/neo4j/Neo4jEmbeddingStoreIT.java
  langchain4j-qdrant/src/main/java/dev/langchain4j/store/embedding/qdrant/QdrantEmbeddingStore.java
  langchain4j/src/test/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStoreTest.java
Labels: Breaking Change

#2791 Remove TokenCountEstimator interfaces
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiTokenizer.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModelIT.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/TokenCountEstimator.java
  langchain4j-core/src/main/java/dev/langchain4j/model/embedding/TokenCountEstimator.java
  langchain4j-core/src/main/java/dev/langchain4j/model/language/TokenCountEstimator.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/TokenCountEstimatorTest.java
  langchain4j-core/src/test/java/dev/langchain4j/model/embedding/TokenCountEstimatorTest.java
  langchain4j-core/src/test/java/dev/langchain4j/model/language/TokenCountEstimatorTest.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModel.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelIT.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiEmbeddingModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiLanguageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingLanguageModel.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
Labels: Breaking Change
