Repository langchain4j/langchain4j, pull requests merged in 2025-08, with the labels that each got.

#2642 use `withFloatVectors` instead of deprecated `withVectors`
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/CollectionRequestBuilder.java
Labels: Dependencies

#3476 Add doc for beforeToolExecution for Token Stream
  docs/docs/tutorials/ai-services.md
Labels: Documentation

#3541 Use a pool of virtual threads as internal default executor
  docs/docs/tutorials/agents.md
  langchain4j-agentic/src/main/java/dev/langchain4j/agentic/AgenticServices.java
  langchain4j-agentic/src/main/java/dev/langchain4j/agentic/declarative/ParallelExecutor.java
  langchain4j-agentic/src/main/java/dev/langchain4j/agentic/workflow/ParallelAgentService.java
  langchain4j-agentic/src/main/java/dev/langchain4j/agentic/workflow/impl/ParallelAgentServiceImpl.java
  langchain4j-agentic/src/test/java/dev/langchain4j/agentic/DeclarativeAgentIT.java
  langchain4j-agentic/src/test/java/dev/langchain4j/agentic/WorkflowAgentsIT.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/DefaultExecutorProvider.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolService.java
Labels: P2, Breaking Change

#3423 Integrate watsonx.ai module
  docs/docs/integrations/language-models/index.md
  docs/docs/integrations/language-models/watsonx.md
  langchain4j-bom/pom.xml
  langchain4j-core/src/main/java/dev/langchain4j/model/ModelProvider.java
  langchain4j-watsonx/pom.xml
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/Converter.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxBuilder.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxChat.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxChatModel.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxChatRequestParameters.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxChatResponseMetadata.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxEmbeddingModel.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxExceptionMapper.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxScoringModel.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxStreamingChatModel.java
  langchain4j-watsonx/src/main/java/dev/langchain4j/model/watsonx/WatsonxTokenCountEstimator.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/ConverterTest.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/WatsonxChatModelTest.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/WatsonxEmbeddingModelTest.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/WatsonxExceptionMapperTest.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/WatsonxScoringModelTest.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/WatsonxStreamingChatModelTest.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/WatsonxTokenCountEstimatorTest.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/it/WatsonxChatModelIT.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/it/WatsonxChatModelListenerIT.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/it/WatsonxStreamingChatModelIT.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/it/WatsonxStreamingChatModelListenerIT.java
  langchain4j-watsonx/src/test/java/dev/langchain4j/model/watsonx/utils/HttpUtils.java
  pom.xml
Labels: P1, P2

#3069 Implement return behavior for tools
  docs/docs/tutorials/tools.md
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/common/BedrockAiServiceWithToolsIT.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ReturnBehavior.java
  langchain4j-core/src/main/java/dev/langchain4j/agent/tool/Tool.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/response/ChatResponse.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/common/MistralAiAiServiceWithToolsIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/common/MistralAiStreamingAiServiceIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/common/OllamaAiServiceWithToolsIT.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceStreamingResponseHandler.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/Result.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolService.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolServiceContext.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolServiceResult.java
  langchain4j/src/test/java/dev/langchain4j/service/common/AbstractAiServiceWithToolsIT.java
  langchain4j/src/test/java/dev/langchain4j/service/common/AbstractStreamingAiServiceIT.java
Labels: P2

#3381 Add support for counting tokens in Anthropic API
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTokenCountEstimator.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicCountTokensRequest.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/MessageTokenCountResponse.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicClient.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/DefaultAnthropicClient.java
  langchain4j-anthropic/src/main/resources/META-INF/native-image/dev.langchain4j/langchain4j-anthropic/reflect-config.json
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicTokenCountEstimatorIT.java
Labels: P2

#3463 Azure CosmosDB No SQL: Sharded DiskANN, Content Retriever Store and Memory Store
  langchain4j-azure-cosmos-nosql/pom.xml
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/AzureCosmosDBNoSqlContentRetriever.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/AzureCosmosDBNoSqlFilterMapper.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/DefaultAzureCosmosDBNoSqlFilterMapper.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/FullTextContains.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/FullTextContainsAll.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/FullTextContainsAny.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AbstractAzureCosmosDBNoSqlEmbeddingStore.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDBNoSqlRuntimeException.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDBSearchQueryType.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDbNoSqlEmbeddingStore.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/MappingUtils.java
  langchain4j-azure-cosmos-nosql/src/main/java/dev/langchain4j/store/memory/azure/cosmos/nosql/AzureCosmosDBNoSqlMemoryStore.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/AzureCosmosDBNoSqlContentRetrieverIT.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/AzureCosmosDBNoSqlContentRetrieverTest.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/rag/content/retriever/azure/cosmos/nosql/DefaultAzureCosmosDBNoSqlFilterMapperTest.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDbNoSqlDocumentTest.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDbNoSqlEmbeddingStoreIT.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/AzureCosmosDbNoSqlEmbeddingStoreTest.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/store/embedding/azure/cosmos/nosql/TestEmbeddingModel.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/store/memory/azure/cosmos/nosql/AzureCosmosDBNoSqlMemoryStoreIT.java
  langchain4j-azure-cosmos-nosql/src/test/java/dev/langchain4j/store/memory/azure/cosmos/nosql/AzureCosmosDBNoSqlMemoryStoreTest.java
  langchain4j-parent/pom.xml
Labels: P2
