Repository langchain4j/langchain4j, pull requests merged in 2025-07, with the labels that each got.

#3280 Refactor Azure OpenAI tests to address flackiness
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureModelBuilders.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelListenerIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiImageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiResponsibleAiIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelListenerIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenCountEstimatorIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenCountEstimatorTest.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelperTest.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiAiServiceIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiAiServiceWithJsonSchemaIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiAiServiceWithToolsIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiStreamingAiServiceIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiStreamingChatModelIT.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/common/AbstractBaseChatModelIT.java
  langchain4j-github-models/src/test/java/dev/langchain4j/model/github/GitHubModelsChatModelIT.java
  langchain4j-google-ai-gemini/pom.xml
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
  langchain4j-parent/pom.xml
  langchain4j-vertex-ai-gemini/pom.xml
Labels: Azure, Testing

#3300 Run integration tests on PR and main only on JDK 21
  .github/workflows/main.yaml
  renovate.json5
Labels: Testing

#3301 Reorder parameters in VespaEmbeddingStore
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaEmbeddingStore.java
  langchain4j-vespa/src/test/java/dev/langchain4j/store/embedding/vespa/VespaEmbeddingStoreTest.java
Labels: bug

#3024 Refactor moderation handling and improve exception details
  docs/docs/tutorials/ai-services.md
  langchain4j-core/src/main/java/dev/langchain4j/model/moderation/Moderation.java
  langchain4j-core/src/main/java/dev/langchain4j/model/moderation/package-info.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/ModerationException.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesModerationTest.java
Labels: enhancement, AI Services, Documentation, Moderation

#3431 Azure OpenAI: removed TokenCountEstimator from streaming models
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelListenerIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiStreamingAiServiceIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiStreamingChatModelIT.java
Labels: Breaking Change

#3179 Fixes #2790: Add callback handler before the tool is executed
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceStreamingResponseHandler.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStream.java
  langchain4j/src/main/java/dev/langchain4j/service/TokenStream.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/BeforeToolExecutionContext.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServiceTokenStreamTest.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesWithToolsIT.java
Labels: P1, P2, Observability
