Repository langchain4j/langchain4j, pull requests merged in 2025-01, with the labels that each got.

#2360 MCP: send the notifications/initialized message
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/ClientMethod.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/InitializationNotification.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/HttpMcpTransport.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/stdio/StdioMcpTransport.java
Labels: P2, MCP

#2364 Modify when memoryid is used
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/MemoryId.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServiceChatMemoryConfigTest.java
Labels: P2, P3

#2303 Azure OpenAI: remove n parameter
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiImageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
Labels: Azure

#2330 Azure OpenAI: propagate all exceptions
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiImageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiResponsibleAiIT.java
Labels: P2, Azure, Breaking Change

#2362 Version upgrade for Milvus integration
  langchain4j-milvus/README.MD
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreIT.java
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreRemovalIT.java
  langchain4j-parent/pom.xml
Labels: P2, P3

#2394 MCP: ping responses and simplification of McpTransport
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/DefaultMcpClient.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/ClientMethod.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/protocol/PingResponse.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/McpOperationHandler.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/McpTransport.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/http/HttpMcpTransport.java
  langchain4j-mcp/src/main/java/dev/langchain4j/mcp/client/transport/stdio/StdioMcpTransport.java
Labels: MCP

#2060 Classpath document source
  docs/docs/integrations/document-loaders/classpath.md
  docs/docs/integrations/document-loaders/file-system.md
  docs/docs/tutorials/rag.md
  langchain4j/pom.xml
  langchain4j/src/main/java/dev/langchain4j/data/document/loader/ClassPathDocumentLoader.java
  langchain4j/src/main/java/dev/langchain4j/data/document/loader/DocumentParserLoader.java
  langchain4j/src/main/java/dev/langchain4j/data/document/loader/FileSystemDocumentLoader.java
  langchain4j/src/main/java/dev/langchain4j/data/document/source/ClassPathSource.java
  langchain4j/src/main/java/dev/langchain4j/data/document/source/FileSystemSource.java
  langchain4j/src/test/externalLib/README.md
  langchain4j/src/test/externalLib/dev/langchain4j/langchain4j-classpath-test-lib/999-SNAPSHOT/_remote.repositories
  langchain4j/src/test/externalLib/dev/langchain4j/langchain4j-classpath-test-lib/999-SNAPSHOT/langchain4j-classpath-test-lib-999-SNAPSHOT.jar
  langchain4j/src/test/externalLib/dev/langchain4j/langchain4j-classpath-test-lib/999-SNAPSHOT/langchain4j-classpath-test-lib-999-SNAPSHOT.pom
  langchain4j/src/test/externalLib/dev/langchain4j/langchain4j-classpath-test-lib/999-SNAPSHOT/maven-metadata-local.xml
  langchain4j/src/test/externalLib/dev/langchain4j/langchain4j-classpath-test-lib/maven-metadata-local.xml
  langchain4j/src/test/java/dev/langchain4j/data/document/loader/ClassPathDocumentLoaderTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/loader/FileSystemDocumentLoaderTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/source/ClassPathSourceTests.java
  langchain4j/src/test/resources/classPathSourceTests/anotherDir/file2.txt
  langchain4j/src/test/resources/classPathSourceTests/banana/test-file-4.banana
  langchain4j/src/test/resources/classPathSourceTests/file1.txt
  langchain4j/src/test/resources/classPathSourceTests/test-file-3.banana
Labels: P2, P3

#2192 Include Metadata after Tika Parsing
  document-parsers/langchain4j-document-parser-apache-tika/src/main/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParser.java
  document-parsers/langchain4j-document-parser-apache-tika/src/test/java/dev/langchain4j/data/document/parser/apache/tika/ApacheTikaDocumentParserTest.java
Labels: P2, P3

#2425 MCP integration tests rework
  .github/workflows/main.yaml
  .github/workflows/nightly_jdk17.yaml
  .github/workflows/nightly_jdk21.yaml
  langchain4j-mcp/pom.xml
  langchain4j-mcp/src/test/java/dev/langchain4j/mcp/client/integration/McpHttpTransportIT.java
  langchain4j-mcp/src/test/java/dev/langchain4j/mcp/client/integration/McpStdioTransportIT.java
  langchain4j-mcp/src/test/java/dev/langchain4j/mcp/client/integration/McpTransportTestBase.java
  langchain4j-mcp/src/test/java/dev/langchain4j/mcp/client/transport/http/McpHttpTransportTest.java
  langchain4j-mcp/src/test/resources/everything/README.md
  langchain4j-mcp/src/test/resources/everything/dist/everything.js
  langchain4j-mcp/src/test/resources/everything/dist/index.js
  langchain4j-mcp/src/test/resources/everything/dist/sse.js
  langchain4j-mcp/src/test/resources/everything/everything.ts
  langchain4j-mcp/src/test/resources/everything/index.ts
  langchain4j-mcp/src/test/resources/everything/package.json
  langchain4j-mcp/src/test/resources/everything/sse.ts
  langchain4j-mcp/src/test/resources/everything/tsconfig.json
  langchain4j-mcp/src/test/resources/logback-test.xml
  langchain4j-mcp/src/test/resources/tools_mcp_server.java
Labels: P2

#2408 fix: Add check for zero norm in normalize() method to handle zero vector
  langchain4j-core/src/main/java/dev/langchain4j/data/embedding/Embedding.java
  langchain4j-core/src/test/java/dev/langchain4j/data/embedding/EmbeddingTest.java
Labels: P2, P3

#2436 Introduce Kotlin custom builders and enhance dependencies
  docs/docs/tutorials/chat-and-language-models.md
  docs/docs/tutorials/kotlin.md
  langchain4j-core/pom.xml
  langchain4j-core/src/main/kotlin/dev/langchain4j/model/chat/ChatLanguageModelExtensions.kt
  langchain4j-core/src/main/kotlin/dev/langchain4j/model/chat/request/ChatRequestExtensions.kt
  langchain4j-core/src/test/kotlin/dev/langchain4j/model/chat/ChatLanguageModelExtensionsTest.kt
  langchain4j-core/src/test/kotlin/dev/langchain4j/model/chat/request/ChatRequestExtensionsTest.kt
  langchain4j-parent/pom.xml
  pom.xml
Labels: enhancement, Kotlin

#2252 [BUG] unable to provide a @Tool with java.lang.UUID in parameters
  langchain4j-core/src/main/java/dev/langchain4j/internal/TypeUtils.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonSchemaElementHelper.java
  langchain4j-core/src/test/java/dev/langchain4j/internal/TypeUtilsTest.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/request/json/JsonSchemaElementHelperTest.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaAiServicesWithJsonSchemaIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithJsonSchemaIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithNewToolsIT.java
Labels: P2, P3

#2450 OpenAI: ensure O1 models are supported
  docs/docs/integrations/language-models/open-ai.md
  docs/docs/tutorials/model-parameters.md
  embedding-store-filter-parsers/langchain4j-embedding-store-filter-parser-sql/src/test/java/dev/langchain4j/store/embedding/filter/builder/sql/LanguageModelSqlFilterBuilderIT.java
  langchain4j-easy-rag/src/test/java/dev/langchain4j/rag/easy/EasyRagIT.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/InternalOpenAiHelper.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModelName.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatRequestParameters.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiTokenizer.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiTokenizerTest.java
  langchain4j-parent/pom.xml
  langchain4j/src/test/java/dev/langchain4j/rag/query/router/LanguageModelQueryRouterIT.java
  langchain4j/src/test/java/dev/langchain4j/rag/query/transformer/CompressingQueryTransformerIT.java
  langchain4j/src/test/java/dev/langchain4j/rag/query/transformer/ExpandingQueryTransformerIT.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesIT.java
  langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesWithToolsWithoutMemoryIT.java
  langchain4j/src/test/java/dev/langchain4j/service/common/openai/OpenAiChatModelIT.java
  langchain4j/src/test/java/dev/langchain4j/service/common/openai/OpenAiStreamingChatModelIT.java
Labels: Breaking Change

#2399 Add the ability to specify a message with the "context" role when using Ollama
  docs/docs/integrations/language-models/ollama.md
  docs/docs/tutorials/chat-and-language-models.md
  langchain4j-core/src/main/java/dev/langchain4j/data/message/ChatMessageType.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/CustomMessage.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/GsonChatMessageJsonCodec.java
  langchain4j-core/src/test/java/dev/langchain4j/data/message/ChatMessageSerializerTest.java
  langchain4j-core/src/test/java/dev/langchain4j/data/message/CustomMessageTest.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/Message.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaMessagesUtils.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/Role.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaCustomMessageChatModelIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaImage.java
Labels: P2

#2344 Support ContainsString metadata Filter
  docs/docs/tutorials/rag.md
  langchain4j-azure-ai-search/src/main/java/dev/langchain4j/rag/content/retriever/azure/search/DefaultAzureAiSearchFilterMapper.java
  langchain4j-azure-ai-search/src/test/java/dev/langchain4j/rag/content/retriever/azure/search/DefaultAzureAiSearchFilterMapperTest.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/Filter.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/MetadataFilterBuilder.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/ContainsString.java
  langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/logical/Not.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithFilteringIT.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/filter/comparison/ContainsStringTest.java
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/filter/logical/NotTest.java
  langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusMetadataFilterMapper.java
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreCloudIT.java
  langchain4j-milvus/src/test/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStoreIT.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/SQLFilters.java
  langchain4j-pgvector/src/main/java/dev/langchain4j/store/embedding/pgvector/PgVectorFilterMapper.java
  langchain4j-pgvector/src/test/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingIndexedStoreIT.java
  langchain4j-pgvector/src/test/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStoreConfigIT.java
  langchain4j-pgvector/src/test/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStoreIT.java
  langchain4j-pinecone/src/test/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStoreIT.java
  langchain4j-qdrant/pom.xml
  langchain4j-qdrant/src/main/java/dev/langchain4j/store/embedding/qdrant/QdrantFilterConverter.java
  langchain4j-qdrant/src/test/java/dev/langchain4j/store/embedding/qdrant/QdrantEmbeddingStoreIT.java
  langchain4j-qdrant/src/test/java/dev/langchain4j/store/embedding/qdrant/QdrantFilterConverterTest.java
  langchain4j/src/test/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStoreSerializedTest.java
  langchain4j/src/test/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStoreTest.java
Labels: P2, P3

#2319 Implemented Bedrock Cohere Embedding
  docs/docs/integrations/embedding-models/amazon-bedrock.md
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockCohereEmbeddingModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockCohereEmbeddingResponse.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockCohereEmbeddingModelIT.java
Labels: P2, P3

#2214 Remove Lombok in LC4J-mistral-ai
  langchain4j-mistral-ai/pom.xml
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiChatModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiEmbeddingModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiModels.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiStreamingChatModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiChatCompletionChoice.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiChatCompletionRequest.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiChatCompletionResponse.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiChatMessage.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiDeltaMessage.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiEmbedding.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiEmbeddingRequest.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiEmbeddingResponse.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiFunction.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiFunctionCall.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiModelCard.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiModelPermission.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiModelResponse.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiParameters.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiResponseFormat.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiResponseFormatType.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiRole.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiTool.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiToolCall.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiUsage.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralCategories.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralCategoryScores.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralModerationResult.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/client/MistralAiRequestLoggingInterceptor.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/client/MistralAiResponseLoggingInterceptor.java
Labels: P2, P3, Mistral

#2404 [feat] Add Bedrock Converse API support
  docs/docs/integrations/language-models/amazon-bedrock.md
  docs/docs/integrations/language-models/index.md
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/AwsDocumentConverter.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/AwsLoggingInterceptor.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/Utils.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/AbstractBedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/internal/Json.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/AwsDocumentConverterTest.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockAiServicesIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockAiServicesWithNewToolsIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelNovaWithVisionIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelWithConverseAPIIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelWithInvokeAPIIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelWithVisionIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelWithoutVisionIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/TestedModelsWithConverseAPI.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/UtilsTest.java
  langchain4j-bedrock/src/test/resources/gemini-doc-snapshot.pdf
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/common/AbstractBaseChatModelIT.java
  langchain4j-parent/pom.xml
Labels: P2

#2381 Upgrade Qdrant client to 1.13.0
  langchain4j-qdrant/pom.xml
Labels: P2, P3

#2466 Fixed "dev.langchain4j.exception" split package
  langchain4j/src/main/java/dev/langchain4j/service/AiServiceTokenStream.java
  langchain4j/src/main/java/dev/langchain4j/service/AiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/IllegalConfigurationException.java
  langchain4j/src/main/java/dev/langchain4j/service/SystemMessage.java
  langchain4j/src/main/java/dev/langchain4j/service/UserMessage.java
  langchain4j/src/main/java/dev/langchain4j/service/output/JsonSchemas.java
  langchain4j/src/main/java/dev/langchain4j/service/output/ServiceOutputParser.java
  langchain4j/src/test/java/dev/langchain4j/exception/IllegalConfigurationExceptionTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServiceChatMemoryConfigTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServiceTokenStreamTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesBuilderTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesSystemAndUserMessageConfigsTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesUserMessageConfigTest.java
  langchain4j/src/test/java/dev/langchain4j/service/output/ServiceOutputParserTest.java
Labels: Breaking Change

#2239 Adding some fixes to the OracleEmbeddingStore
  docs/docs/integrations/embedding-stores/oracle.md
  langchain4j-oracle/README.md
  langchain4j-oracle/pom.xml
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/EmbeddingTable.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/IVFIndexBuilder.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/Index.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/IndexBuilder.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/JSONIndexBuilder.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/OracleEmbeddingStore.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/SQLFilter.java
  langchain4j-oracle/src/main/java/dev/langchain4j/store/embedding/oracle/SQLFilters.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/CommonTestOperations.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/EmbeddingIndexStoreWithFilteringIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/EmbeddingIndexStoreWithRemovalIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/EmbeddingTableIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/MetadataAndEmbeddingIndexStoreWithFilteringIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/MetadataAndEmbeddingIndexStoreWithRemovalIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/MetadataIndexStoreWithFilteringIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/MetadataIndexStoreWithRemovalIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/OracleEmbeddingStoreIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/OracleEmbeddingStoreWithFilteringIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/OracleEmbeddingStoreWithRemovalIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/SQLFilterIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/SQLFilterTest.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/VectorIndexIT.java
  langchain4j-oracle/src/test/java/dev/langchain4j/store/embedding/oracle/VectorIndexTest.java
Labels: P2, P3

#2387 fix #2385
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java
Labels: P2, P3, Azure

#1773 Chroma: Migrate from Gson to Jackson - WIP
  langchain4j-chroma/pom.xml
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/AddEmbeddingsRequest.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaClient.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStore.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/Collection.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/CreateCollectionRequest.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/QueryRequest.java
  langchain4j-chroma/src/main/java/dev/langchain4j/store/embedding/chroma/QueryResponse.java
  langchain4j-chroma/src/test/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStoreIT.java
  langchain4j-chroma/src/test/java/dev/langchain4j/store/embedding/chroma/ChromaEmbeddingStoreRemovalIT.java
Labels: P2, P3

#2056 migrate vespa to jackson + tests and refactorings
  langchain4j-core/src/test/java/dev/langchain4j/store/embedding/EmbeddingStoreWithoutMetadataIT.java
  langchain4j-vespa/pom.xml
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/DeleteResponse.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/QueryResponse.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/Record.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaApi.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaClient.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaEmbeddingStore.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaQueryApi.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaQueryClient.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaRequestLoggingInterceptor.java
  langchain4j-vespa/src/main/java/dev/langchain4j/store/embedding/vespa/VespaResponseLoggingInterceptor.java
  langchain4j-vespa/src/test/java/dev/langchain4j/store/embedding/vespa/VespaEmbeddingStoreCloudIT.java
  langchain4j-vespa/src/test/java/dev/langchain4j/store/embedding/vespa/VespaEmbeddingStoreIT.java
  langchain4j-vespa/src/test/resources/tinylog.properties
  langchain4j-vespa/src/test/resources/vespa_app.zip
Labels: P2, P3

#2368 upgrade-pinecone-and-add-ability-to-protect-deletion-index
  langchain4j-pinecone/pom.xml
  langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStore.java
  langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeServerlessIndexConfig.java
Labels: P2, P3

#2325 docs: clarify exclusion of metadata from equals and hashCode in Conte…
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/Content.java
Labels: P2, P3

#1988 #1946 Convert Document and Content to interfaces
  langchain4j-core/src/main/java/dev/langchain4j/data/document/DefaultDocument.java
  langchain4j-core/src/main/java/dev/langchain4j/data/document/Document.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/Content.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/DefaultContent.java
  langchain4j-core/src/main/java/dev/langchain4j/rag/content/aggregator/ReRankingContentAggregator.java
  langchain4j-core/src/test/java/dev/langchain4j/data/document/DocumentTest.java
  langchain4j-core/src/test/java/dev/langchain4j/rag/content/ContentTest.java
Labels: P2, P3, Breaking Change
