Repository langchain4j/langchain4j, pull requests merged in 2025-06, with the labels that each got.

#3097 Fix flaky OpenAiStreamingChatModelErrorsTest
  .github/workflows/main.yaml
  Makefile
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelErrorsTest.java
  langchain4j-parent/pom.xml
Labels: Testing, Dependencies

#3127 Fix spotless plugin run on CI and in Makefile
  Makefile
Labels: good first issue

#3030 #3029: Add support to structured output to Vertex AI gemini
  langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/gemini/VertexAiGeminiChatModel.java
  langchain4j-vertex-ai-gemini/src/test/java/dev/langchain4j/model/vertexai/gemini/VertexAiGeminiChatModelIT.java
Labels: Gemini

#3155 Azure OpenAI: prepare for 1.0
  docs/docs/integrations/language-models/azure-open-ai.md
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModel.java
  langchain4j-azure-open-ai/pom.xml
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiEmbeddingModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiImageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiModelName.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiTokenCountEstimator.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiExceptionMapper.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiStreamingResponseBuilder.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelListenerIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiResponsibleAiIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelListenerIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenCountEstimatorIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiAiServiceIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiAiServiceWithToolsIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiStreamingAiServiceIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiStreamingChatModelIT.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/ChatModel.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/StreamingChatModel.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/DefaultChatRequestParameters.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/common/AbstractBaseChatModelIT.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaBaseChatModel.java
  langchain4j-open-ai-official/src/main/java/dev/langchain4j/model/openaiofficial/OpenAiOfficialBaseChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelWithJsonSchemaIT.java
  langchain4j/src/test/java/dev/langchain4j/service/common/AbstractStreamingAiServiceIT.java
Labels: Breaking Change

#3202 Google AI Gemini: use HttpClient abstraction
  docs/docs/integrations/language-models/index.md
  langchain4j-google-ai-gemini/pom.xml
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/BaseGeminiChatModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GeminiService.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiEmbeddingModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiStreamingChatModel.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiTokenCountEstimator.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/Json.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelListenerIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiStreamingChatModelListenerIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/common/GoogleAiGeminiAiServiceIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/common/GoogleAiGeminiChatModelIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/common/GoogleAiGeminiStreamingChatModelIT.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/log/HttpRequestLogger.java
Labels: Breaking Change

#3221 Anthropic: prepare for 1.0
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModel.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/AnthropicTokenUsage.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/InternalAnthropicHelper.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicThinking.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/api/AnthropicToolChoice.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicClient.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicClientBuilderFactory.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/AnthropicToolExecutionRequestBuilder.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/DefaultAnthropicClient.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/client/Json.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/mapper/AnthropicMapper.java
  langchain4j-anthropic/src/main/java/dev/langchain4j/model/anthropic/internal/sanitizer/MessageSanitizer.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicStreamingChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/common/AnthropicChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/common/AnthropicStreamingChatModelIT.java
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/internal/sanitizer/MessageSanitizerTest.java
Labels: Breaking Change
