Repository langchain4j/langchain4j, pull requests merged in 2025-04, with the labels that each got.

#2792 OpenAI: remove deprecated APIs
  docs/docs/integrations/language-models/open-ai.md
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/memory/chat/cassandra/CassandraChatMemoryStoreTestSupport.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiEmbeddingModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiImageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiLanguageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiModelName.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiModerationModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingLanguageModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiTokenizer.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/internal/chat/ChatCompletionRequest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/DocumentByParagraphSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/DocumentBySentenceSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/internal/TestUtils.java
  langchain4j/src/test/java/dev/langchain4j/memory/chat/TokenWindowChatMemoryTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithRagIT.java
Labels: Breaking Change

#2730 Add support for Jackson Kotlin module and improve JSON handling
  .editorconfig
  docs/docs/tutorials/kotlin.md
  langchain4j-core/pom.xml
  langchain4j-core/src/main/java/dev/langchain4j/internal/JacksonJsonCodec.java
  langchain4j-core/src/test/kotlin/dev/langchain4j/internal/JacksonJsonCodecTest.kt
  langchain4j-parent/pom.xml
  langchain4j/pom.xml
Labels: bug, Kotlin

#2720 Upgrade version of Azure OpenAI to 1.0.0-beta.16
  langchain4j-parent/pom.xml
Labels: Dependencies

#2620 Add ConverseStream support for Amazon Bedrock integrations
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/AbstractBedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/AwsDocumentConverter.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockChatRequestParameters.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/BedrockStreamingChatModel.java
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/ConverseResponseFromStreamBuilder.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockChatModelWithConverseAPIIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockStreamingChatModelListenerWithConverseIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/BedrockStreamingChatModelWithConverseIT.java
  langchain4j-bedrock/src/test/java/dev/langchain4j/model/bedrock/TestedModelsWithConverseAPI.java
  langchain4j-parent/pom.xml
Labels: Streaming, AWS Bedrock

#2874 Rename Tokenizer into TokenCountEstimator
  docs/docs/integrations/language-models/open-ai.md
  docs/docs/integrations/language-models/qianfan.md
  docs/docs/tutorials/chat-memory.md
  docs/docs/tutorials/rag.md
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingResponseBuilder.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiTokenCountEstimator.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiStreamingLanguageModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenCountEstimatorIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiTokenCountEstimatorTest.java
  langchain4j-cassandra/src/test/java/dev/langchain4j/store/memory/chat/cassandra/CassandraChatMemoryStoreTestSupport.java
  langchain4j-core/src/main/java/dev/langchain4j/model/TokenCountEstimator.java
  langchain4j-core/src/test/java/dev/langchain4j/model/ExampleTestTokenCountEstimator.java
  langchain4j-easy-rag/src/main/java/dev/langchain4j/data/document/splitter/recursive/RecursiveDocumentSplitterFactory.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/GoogleAiGeminiTokenCountEstimator.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiTokenCountEstimatorIT.java
  langchain4j-open-ai-official/src/main/java/dev/langchain4j/model/openaiofficial/OpenAiOfficialBaseChatModel.java
  langchain4j-open-ai-official/src/main/java/dev/langchain4j/model/openaiofficial/OpenAiOfficialChatModel.java
  langchain4j-open-ai-official/src/main/java/dev/langchain4j/model/openaiofficial/OpenAiOfficialStreamingChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiTokenCountEstimator.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiTokenCountEstimatorIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiTokenCountEstimatorTest.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentByCharacterSplitter.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentByLineSplitter.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentByParagraphSplitter.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentByRegexSplitter.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentBySentenceSplitter.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentByWordSplitter.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentSplitters.java
  langchain4j/src/main/java/dev/langchain4j/data/document/splitter/HierarchicalDocumentSplitter.java
  langchain4j/src/main/java/dev/langchain4j/memory/chat/TokenWindowChatMemory.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/DocumentByParagraphSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/DocumentBySentenceSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/data/document/splitter/HierarchicalDocumentSplitterTest.java
  langchain4j/src/test/java/dev/langchain4j/internal/TestUtils.java
  langchain4j/src/test/java/dev/langchain4j/memory/chat/TokenWindowChatMemoryTest.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithRagIT.java
Labels: Breaking Change

#2906 Fixed https://github.com/langchain4j/langchain4j/issues/2794
  http-clients/langchain4j-http-client-jdk/src/main/java/dev/langchain4j/http/client/jdk/JdkHttpClient.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/sse/DefaultServerSentEventParser.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/sse/ServerSentEventListenerUtils.java
  langchain4j-http-client/src/test/java/dev/langchain4j/http/client/HttpClientIT.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaServerSentEventParser.java
Labels: Breaking Change

#2908 Removed redundant TextFile and TextFileContent
  docs/docs/integrations/language-models/google-ai-gemini.md
  langchain4j-bedrock/src/main/java/dev/langchain4j/model/bedrock/AbstractBedrockChatModel.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/Content.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/ContentType.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/JacksonChatMessageJsonCodec.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/TextFileContent.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/UserMessage.java
  langchain4j-core/src/main/java/dev/langchain4j/data/text/TextFile.java
  langchain4j-core/src/test/java/dev/langchain4j/data/message/ChatMessageSerializerTest.java
  langchain4j-google-ai-gemini/src/main/java/dev/langchain4j/model/googleai/PartsAndContentsMapper.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiChatModelIT.java
  langchain4j-google-ai-gemini/src/test/java/dev/langchain4j/model/googleai/GoogleAiGeminiStreamingChatModelIT.java
Labels: Breaking Change

#2936 Downgrade kotlinx-coroutines to version 1.8.1
  langchain4j-parent/pom.xml
Labels: Kotlin, Dependencies
