Repository langchain4j/langchain4j, pull requests merged in 2025-05, with the labels that each got.

#2945 Fix Kotlin settings
  Makefile
  langchain4j-kotlin/pom.xml
  langchain4j-parent/pom.xml
Labels: bug, Tools, Kotlin, Documentation

#2957 Update Kotlin compiler to 2.1.20 and enforce stricter checks
  .mvn/maven.config
  langchain4j-parent/pom.xml
Labels: enhancement, Kotlin

#2717 Add timeout handling test and update dependencies
  langchain4j-anthropic/src/test/java/dev/langchain4j/model/anthropic/AnthropicChatModelErrorsTest.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelErrorsTest.java
Labels: Testing, Dependencies

#2956 Enhance virtual threads support in Kotlin Coroutines
  langchain4j-core/src/main/java/dev/langchain4j/internal/VirtualThreadUtils.java
  langchain4j-core/src/test/kotlin/dev/langchain4j/internal/VirtualThreadUtilsTest.kt
  langchain4j-kotlin/src/main/kotlin/dev/langchain4j/kotlin/model/chat/ChatModelExtensions.kt
  langchain4j-kotlin/src/test/kotlin/dev/langchain4j/kotlin/model/chat/ChatModelExtensionsTest.kt
Labels: enhancement, Kotlin

#2981 Ollama: return `FinishReason.TOOL_EXECUTION` when tool calls are present in the response
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/InternalOllamaHelper.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingResponseBuilder.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiChatModelIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaOpenAiStreamingChatModelIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/common/OllamaAiServiceIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/common/OllamaChatModelIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/common/OllamaStreamingChatModelIT.java
Labels: Breaking Change

#2987 Fix: OpenAI: fail if `topK` parameter is specified
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java
  langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
Labels: Breaking Change

#2951 Reflection variable resolver
  langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java
  langchain4j/src/main/java/dev/langchain4j/service/InternalReflectionVariableResolver.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServiceThrowingExceptionIT.java
  langchain4j/src/test/java/dev/langchain4j/service/InternalReflectionVariableResolverTest.java
  langchain4j/src/test/java/dev/langchain4j/service/common/AbstractStreamingAiServiceIT.java
  langchain4j/src/test/java/dev/langchain4j/service/common/openai/OpenAiAiServiceIT.java
  langchain4j/src/test/java/dev/langchain4j/service/common/openai/OpenAiStreamingAiServiceIT.java
Labels: AI Services, Testing

#3061 Fix #3018, #3028 and #3055
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolExecutionRequestUtil.java
  langchain4j/src/test/java/dev/langchain4j/service/tool/ToolExecutionRequestUtilTest.java
Labels: P1

#1569 Mistral AI: Support fill-in-the-middle API for code completion models
  docs/docs/integrations/language-models/mistral-ai.md
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiChatModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiChatModelName.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiFimModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiFimModelName.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiModerationModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiStreamingChatModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiStreamingFimModel.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiApi.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiCategories.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiCategoryScores.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiFimCompletionRequest.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiJsonSchema.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiModerationResponse.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/api/MistralAiModerationResult.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/client/DefaultMistralAiClient.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/client/MistralAiClient.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/internal/mapper/MistralAiMapper.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/spi/MistralAiFimModelBuilderFactory.java
  langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/spi/MistralAiStreamingFimModelBuilderFactory.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiChatModelIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiEmbeddingModelIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiFimModelIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiStreamingChatModelIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/MistralAiStreamingFimModelIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/common/MistralAiAiServiceIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/common/MistralAiAiServiceWithJsonSchemaIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/common/MistralAiAiServiceWithToolsIT.java
  langchain4j-mistral-ai/src/test/java/dev/langchain4j/model/mistralai/common/MistralAiStreamingAiServiceIT.java
Labels: P3, Mistral
