Repository langchain4j/langchain4j, pull requests merged in 2025-02, with the labels that each got.

#2492 Migrate `langchain4j-redis`
  docs/docs/integrations/embedding-stores/redis.md
  langchain4j-bom/pom.xml
  langchain4j-parent/pom.xml
  langchain4j-redis/pom.xml
  langchain4j-redis/src/main/java/dev/langchain4j/store/embedding/redis/MetricType.java
  langchain4j-redis/src/main/java/dev/langchain4j/store/embedding/redis/RedisEmbeddingStore.java
  langchain4j-redis/src/main/java/dev/langchain4j/store/embedding/redis/RedisRequestFailedException.java
  langchain4j-redis/src/main/java/dev/langchain4j/store/embedding/redis/RedisSchema.java
  langchain4j-redis/src/main/java/dev/langchain4j/store/memory/chat/redis/RedisChatMemoryStore.java
  langchain4j-redis/src/main/java/dev/langchain4j/store/memory/chat/redis/RedisChatMemoryStoreException.java
  langchain4j-redis/src/test/java/dev/langchain4j/store/embedding/redis/RedisEmbeddingStoreIT.java
  langchain4j-redis/src/test/java/dev/langchain4j/store/memory/chat/redis/RedisChatMemoryStoreIT.java
  pom.xml
Labels: Breaking Change

#2334 Azure OpenAI: add support for Structured Outputs in StreamingChatModel
  langchain4j-azure-open-ai/pom.xml
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java
  langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiAiServicesWithJsonSchemaIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiChatModelIT.java
  langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/common/AzureOpenAiStreamingChatModelIT.java
  langchain4j-core/src/main/java/dev/langchain4j/model/chat/request/json/JsonSchemaElementHelper.java
  langchain4j-core/src/test/java/dev/langchain4j/model/chat/common/AbstractStreamingChatModelIT.java
Labels: P2, P3, Azure

#2225 Here is the MariaDB database store implementation.
  docs/docs/integrations/embedding-stores/mariadb.md
  langchain4j-bom/pom.xml
  langchain4j-mariadb/pom.xml
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/ColumnFilterMapper.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/ColumnsMetadataHandler.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/DefaultMetadataStorageConfig.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/JSONFilterMapper.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/JSONMetadataHandler.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MariaDBDistanceType.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingStore.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MariaDbFilterMapper.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MariaDbValidator.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MetadataColumDefinition.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MetadataHandler.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MetadataHandlerFactory.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MetadataStorageConfig.java
  langchain4j-mariadb/src/main/java/dev/langchain4j/store/embedding/mariadb/MetadataStorageMode.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/JSONMetadataHandlerTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingCustomNamingTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingIndexedStoreTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingStoreConfigTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingStoreRemovalTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingStoreTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingStoreUpgradeTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingStoreWithColumnsFilteringTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbEmbeddingStoreWithJSONFilteringTest.java
  langchain4j-mariadb/src/test/java/dev/langchain4j/store/embedding/mariadb/MariaDbTests.java
  langchain4j-mariadb/src/test/resources/logback-test.xml
  pom.xml
Labels: P2, P3

#2413 Customizable HTTP clients
  http-clients/langchain4j-http-client-jdk/pom.xml
  http-clients/langchain4j-http-client-jdk/src/main/java/dev/langchain4j/http/client/jdk/JdkHttpClient.java
  http-clients/langchain4j-http-client-jdk/src/main/java/dev/langchain4j/http/client/jdk/JdkHttpClientBuilder.java
  http-clients/langchain4j-http-client-jdk/src/main/java/dev/langchain4j/http/client/jdk/JdkHttpClientBuilderFactory.java
  http-clients/langchain4j-http-client-jdk/src/main/resources/META-INF/services/dev.langchain4j.http.client.HttpClientBuilderFactory
  http-clients/langchain4j-http-client-jdk/src/test/java/dev/langchain4j/http/client/jdk/JdkHttpClientIT.java
  http-clients/langchain4j-http-client-jdk/src/test/java/dev/langchain4j/http/client/jdk/JdkHttpClientTimeoutIT.java
  langchain4j-bom/pom.xml
  langchain4j-core/pom.xml
  langchain4j-core/src/main/java/dev/langchain4j/exception/HttpException.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/ValidationUtils.java
  langchain4j-core/src/test/java/dev/langchain4j/internal/ValidationUtilsTest.java
  langchain4j-http-client/pom.xml
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/HttpClient.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/HttpClientBuilder.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/HttpClientBuilderFactory.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/HttpClientBuilderLoader.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/HttpMethod.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/HttpRequest.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/SuccessfulHttpResponse.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/log/HttpRequestLogger.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/log/HttpResponseLogger.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/log/LoggingHttpClient.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/sse/ServerSentEvent.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/sse/ServerSentEventListener.java
  langchain4j-http-client/src/main/java/dev/langchain4j/http/client/sse/ServerSentEventParser.java
  langchain4j-http-client/src/test/java/dev/langchain4j/http/client/DefaultServerSentEventParser.java
  langchain4j-http-client/src/test/java/dev/langchain4j/http/client/HttpClientIT.java
  langchain4j-http-client/src/test/java/dev/langchain4j/http/client/HttpClientTimeoutIT.java
  langchain4j-http-client/src/test/java/dev/langchain4j/http/client/HttpRequestTest.java
  langchain4j-ollama/pom.xml
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaApi.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaEmbeddingModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaJsonUtils.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaLanguageModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaMessagesUtils.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaModels.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaRequestLoggingInterceptor.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaResponseLoggingInterceptor.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaServerSentEventParser.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingChatModel.java
  langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaStreamingLanguageModel.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaApiIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaChatModelVisionIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaStreamingChatModelIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaStreamingChatModelListenerIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaStreamingLanguageModelIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaStructuredOutputIT.java
  langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaToolChatModelIT.java
  langchain4j-parent/pom.xml
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithNewToolsIT.java
  pom.xml
Labels: P1, Breaking Change

#2520 Add support for StreamingChatLanguageModel.chat with flow response
  langchain4j-core/src/main/java/dev/langchain4j/internal/Markers.java
  langchain4j-core/src/main/kotlin/dev/langchain4j/model/chat/ChatLanguageModelExtensions.kt
  langchain4j-core/src/main/kotlin/dev/langchain4j/model/chat/StreamingChatLanguageModelExtensions.kt
  langchain4j-core/src/test/kotlin/dev/langchain4j/model/chat/StreamingChatLanguageModelExtensionsKtTest.kt
Labels: enhancement, Kotlin

#2525 Add Kotlin streaming use case documentation, update test
  docs/docs/tutorials/kotlin.md
  langchain4j-core/src/test/kotlin/dev/langchain4j/model/chat/StreamingChatLanguageModelExtensionsKtTest.kt
Labels: Kotlin, Documentation

#2595 Migrate from Gson to Jackson
  docs/docs/tutorials/structured-outputs.md
  langchain4j-core/pom.xml
  langchain4j-core/src/main/java/dev/langchain4j/data/message/AiMessage.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/ChatMessageSerializer.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/Content.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/GsonChatMessageAdapter.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/GsonChatMessageJsonCodec.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/GsonContentAdapter.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/JacksonChatMessageJsonCodec.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/PdfFileContent.java
  langchain4j-core/src/main/java/dev/langchain4j/data/message/UserMessage.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/GsonJsonCodec.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/JacksonJsonCodec.java
  langchain4j-core/src/main/java/dev/langchain4j/internal/Json.java
  langchain4j-core/src/main/java/dev/langchain4j/model/input/structured/DefaultStructuredPromptFactory.java
  langchain4j-core/src/test/java/dev/langchain4j/data/message/ChatMessageSerializerTest.java
  langchain4j-core/src/test/java/dev/langchain4j/internal/GsonJsonCodecTest.java
  langchain4j-core/src/test/java/dev/langchain4j/internal/JsonCodecTest.java
  langchain4j-core/src/test/java/dev/langchain4j/internal/JsonTest.java
  langchain4j-core/src/test/java/dev/langchain4j/model/input/structured/StructuredPromptProcessorTest.java
  langchain4j-google-ai-gemini/pom.xml
  langchain4j-jlama/src/main/java/dev/langchain4j/model/jlama/JlamaChatModel.java
  langchain4j-jlama/src/main/java/dev/langchain4j/model/jlama/JlamaStreamingChatModel.java
  langchain4j-jlama/src/main/java/dev/langchain4j/model/jlama/Json.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiChatModelIT.java
  langchain4j-open-ai/src/test/java/dev/langchain4j/model/openai/OpenAiStreamingChatModelIT.java
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/Json.java
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiChatModel.java
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiEmbeddingModel.java
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiImageModel.java
  langchain4j-vertex-ai/src/main/java/dev/langchain4j/model/vertexai/VertexAiLanguageModel.java
  langchain4j/pom.xml
  langchain4j/src/main/java/dev/langchain4j/service/tool/DefaultToolExecutor.java
  langchain4j/src/main/java/dev/langchain4j/service/tool/ToolExecutionRequestUtil.java
  langchain4j/src/main/java/dev/langchain4j/store/embedding/inmemory/GsonInMemoryEmbeddingStoreJsonCodec.java
  langchain4j/src/main/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStore.java
  langchain4j/src/main/java/dev/langchain4j/store/embedding/inmemory/JacksonInMemoryEmbeddingStoreJsonCodec.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithJsonSchemaIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithJsonSchemaWithDescriptionsIT.java
  langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java
  langchain4j/src/test/java/dev/langchain4j/service/TypeUtilsTest.java
  langchain4j/src/test/java/dev/langchain4j/service/output/JsonSchemasTest.java
  langchain4j/src/test/java/dev/langchain4j/service/output/ServiceOutputParserTest.java
  langchain4j/src/test/java/dev/langchain4j/service/tool/DefaultToolExecutorTest.java
  langchain4j/src/test/java/dev/langchain4j/service/tool/ToolExecutionRequestUtilTest.java
Labels: Breaking Change
